### ISSUE TITLE
Discord server for this plugin

### ISSUE THREAD

**Issue by hiddos** [maddinat0r/samp-discord-connector#1]
Since this is a plugin for a Discord server, I think there should be a Discord server/guild. I can make one and link it, but I figured it might be more suitable if @maddinat0r does it since he's the repository owner as well.

**Comment by Crayder** [comment]
Umm... Like a central server for all users to use or just an example server?

A central server would be nice for like all SA-MP players to use but obviously that'd be a wreck.
SA-MP server owners would likely prefer personal servers.

**Comment by maddinat0r** [comment]
I don't really see a reason why there should be a Discord server dedicated to this plugin. There's GitHub for issues and the official SA-MP forum for discussion.

**Comment by hiddos** [comment]
Ah, I forgot we had the forum for that as well. I mainly intended it for discussion (and keeping issues here), but the SA-MP forum is probably better suited for that. I'll close this then.
