### ISSUE TITLE
Run time error 19: "File or function is not found"

### ISSUE THREAD

**Issue by bubyygh** [maddinat0r/samp-discord-connector#100]
![image](https://user-images.githubusercontent.com/44922729/63688244-1db15d00-c807-11e9-93f8-a3ef63866a15.png)

Removing the newer functions from the script fixes the problem. But I need the new functions lol
I updated everything to the latest version.

**Comment by bubyygh** [comment]
Btw the server runs fine with the new function "DCC_DeleteGuildRole", but doesn't with the other new functions, I don't get it

**Comment by bubyygh** [comment]
I downloaded ALL redistributables, nothing helps. Using the newest version of discord connector works fine only when I remove these newer functions from the script. HELP

**Comment by maddinat0r** [comment]
Are you absolutely sure you recompiled your gamemode with the newest plugin include?

**Comment by bubyygh** [comment]
Absolutely. Several times. Doesn't work on linux either.

**Comment by maddinat0r** [comment]
Oh boy. I forgot to register 15 natives in the plugin (fixed now in 1463ec3ba14d34c0b975e0405b93127af5e38e98). That's what I get for not using more modern libraries to handle that (pawn-natives 👀). I'm sorry for any inconvenience caused. I'll re-release v0.3 with the fix ASAP.

**Comment by maddinat0r** [comment]
It's now re-released with the fix included.

**Comment by hassouna121** [comment]
@maddinat0r i have problem when i start the server i have this debugs
![image](https://user-images.githubusercontent.com/124177622/216086132-da8ce50e-dc27-44fb-a86e-b7b9378f634b.png)
