### ISSUE TITLE
Polish letters block messages

### ISSUE THREAD

**Issue by b4ll** [maddinat0r/samp-discord-connector#101]
```
public OnPlayerText(playerid, text[])
{
	new lName[32], lString[150];
	GetPlayerName(playerid, lName, 32);
	format(lString, sizeof lString, "[ID: %d] [%s] -> %s", playerid, lName, text);
	print(lString);
	DCC_SendChannelMessage(gDiscordChat, lString);
	return 1;
}
```

There is a bug with polish letters like ą, ś, ć, ł and others. When player text message that contain polish letter then callback DCC_OnMessageCreate isn't called. Messages without polish letters work fine.

**Comment by bubyygh** [comment]
One question, not related to this. Are you using the newest version of DCC? If you are, do the newer functions work for you (e.g. DCC_AddGuildMemberRole), or are you [getting erros when using them](https://github.com/maddinat0r/samp-discord-connector/issues/100)?

**Comment by b4ll** [comment]
Yes, I am using the newest one but I don't use these functions. I just got started in discord plugin.

**Comment by maddinat0r** [comment]
Are there any errors in the `discord-connector.log` file?

**Comment by b4ll** [comment]
Sorry for late reply, but yeah, there is something in the file.

`[09/01/19 19:29:41] [ERROR] Error while retrieving HTTP POST response from '/api/v6/channels/615536391119699981/messages': end of stream
[09/01/19 19:29:49] [ERROR] can't serialize JSON: [json.exception.type_error.316] invalid UTF-8 byte at index 30: 0x9C
`

**Comment by marcelog09** [comment]
I have the same problem for Portuguese / Brazil, which have accentuation ( á, à ã, é ... ):

[09/07/19 17:29:28] [ERROR] can't serialize JSON: [json.exception.type_error.316] incomplete UTF-8 string; last byte: 0xE9

Is there a solution?

**Comment by b4ll** [comment]
Any news about this issue? I tried other formats in notepad like UTF-8 or ANSI but no progress.

**Comment by kubkodev** [comment]
@b4ll maddinat0r already said in #27 he won't add platform dependent code for the conversion, what makes sense. I ran into simillar issue, I needed to display country (Czech & Slovak) characters correctly too. We share same charset (central Europe), so you can use this function from my fork: https://github.com/kubkodev/samp-discord-connector/blob/master/discord-encoding.inc

**Comment by b4ll** [comment]
@kubkodev your function doesn't work with polish letters, but now I have idea how to do it properly. Thanks for the tip.
