### ISSUE TITLE
DCC_OnMessageCreate

### ISSUE THREAD

**Issue by Steve571** [maddinat0r/samp-discord-connector#108]
Well i just wanna know how does this function actually work i mean isn't message supposed to be in a string format i don't really get how this function works if u could give me a hint would be thankful,

Thanks in advanced

**Comment by kubkodev** [comment]
Well, basically in `DCC_OnMessageCreate` callback you're getting PAWN ID (not the actual message id) as a `message` parameter of type `DCC_Message`. With this available you can do anything what you want. Check include file for all implemented PAWN natives related to messages. And not suprisingly `DCC_GetMessageContent` is one of them. In the following snippet you can take a look how it works.
```pawn
public DCC_OnMessageCreate(DCC_Message:message)
{
    new content[64];
    DCC_GetMessageContent(message, content);
    print(conten);
}
```

**Comment by maddinat0r** [comment]
Just as @kubkodev said. A Discord message has a lot more information than just the message itself. You currently can get the author, the channel the message was sent in, all user and role mentions and check if it is a TTS message or if there's a `@everyone` mention in it.
