### ISSUE TITLE
[WIN] Errors with SSL libraries when Compiling

### ISSUE THREAD

**Issue by Faskis** [maddinat0r/samp-discord-connector#11]
I'm getting the following issues whenever I attempt to compile:

>1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/libs/cppformat/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/libs/cppformat/fmt/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/src/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/src/amx/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/Development/SA-MP/samp-discord-connector/build/src/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: amx, Configuration: Debug Win32 ------
3>------ Build started: Project: fmt, Configuration: Debug Win32 ------
2>  Building Custom Rule E:/Development/SA-MP/samp-discord-connector/libs/samp-log-core/src/amx/CMakeLists.txt
2>  CMake does not need to re-run because E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\src\amx\CMakeFiles\generate.stamp is up-to-date.
2>  amx.c
2>  amxaux.c
2>  amxdbg.c
2>  Generating Code...
3>  Building Custom Rule E:/Development/SA-MP/samp-discord-connector/libs/samp-log-core/libs/cppformat/fmt/CMakeLists.txt
3>  CMake does not need to re-run because E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\libs\cppformat\fmt\CMakeFiles\generate.stamp is up-to-date.
2>  amxplugin2.cpp
3>  posix.cc
3>  format.cc
2>  amx.vcxproj -> E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\src\amx\Debug\amx.lib
3>  ostream.cc
3>  Generating Code...
3>  fmt.vcxproj -> E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\libs\cppformat\fmt\Debug\fmt.lib
4>------ Build started: Project: log-core, Configuration: Debug Win32 ------
4>  Building Custom Rule E:/Development/SA-MP/samp-discord-connector/libs/samp-log-core/src/CMakeLists.txt
4>  CMake does not need to re-run because E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\src\CMakeFiles\generate.stamp is up-to-date.
4>  CAmxDebugManager.cpp
4>  CSampConfigReader.cpp
4>  CLogger.cpp
4>  crashhandler_windows.cpp
4>  Generating Code...
4>     Creating library E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/src/Debug/log-core.lib and object E:/Development/SA-MP/samp-discord-connector/build/libs/samp-log-core/src/Debug/log-core.exp
4>  log-core.vcxproj -> E:\Development\SA-MP\samp-discord-connector\build\libs\samp-log-core\src\Debug\log-core.dll
5>------ Build started: Project: discord-connector, Configuration: Debug Win32 ------
5>  Building Custom Rule E:/Development/SA-MP/samp-discord-connector/src/CMakeLists.txt
5>  CMake does not need to re-run because E:\Development\SA-MP\samp-discord-connector\build\src\CMakeFiles\generate.stamp is up-to-date.
5>  amxplugin.cpp
5>  amxplugin2.cpp
5>  CCallback.cpp
5>  CChannel.cpp
5>  CDispatcher.cpp
5>  CLog.cpp
5>  CMessage.cpp
5>  CNetwork.cpp
5>C:\Program Files (x86)\boost\boost_1_63_0\boost/spirit/home/support/detail/endian/endian.hpp(55): warning C4005: 'BOOST_ENDIAN_DEFAULT_CONSTRUCT': macro redefinition
5>  C:\Program Files (x86)\boost\boost_1_63_0\boost/endian/buffers.hpp(54): note: see previous definition of 'BOOST_ENDIAN_DEFAULT_CONSTRUCT'
5>  main.cpp
5>  natives.cpp
5>C:\Program Files (x86)\boost\boost_1_63_0\boost/spirit/home/support/detail/endian/endian.hpp(55): warning C4005: 'BOOST_ENDIAN_DEFAULT_CONSTRUCT': macro redefinition
5>  C:\Program Files (x86)\boost\boost_1_63_0\boost/endian/buffers.hpp(54): note: see previous definition of 'BOOST_ENDIAN_DEFAULT_CONSTRUCT'
5>  Generating Code...
5>  getch.c
5>     Creating library E:/Development/SA-MP/samp-discord-connector/build/src/Debug/discord-connector.lib and object E:/Development/SA-MP/samp-discord-connector/build/src/Debug/discord-connector.exp
5>libcrypto32MDd.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp__sscanf referenced in function _OPENSSL_cpuid_setup
5>libcrypto32MDd.lib(v3_utl.obj) : error LNK2001: unresolved external symbol __imp__sscanf
5>libcrypto32MDd.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp___vsnprintf referenced in function _OPENSSL_showfatal
5>libcrypto32MDd.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp___vsnwprintf referenced in function _OPENSSL_showfatal
5>libcrypto32MDd.lib(pem_lib.obj) : error LNK2019: unresolved external symbol __imp____iob_func referenced in function _PEM_def_callback
5>libcrypto32MDd.lib(eng_openssl.obj) : error LNK2001: unresolved external symbol __imp____iob_func
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp____iob_func
5>libcrypto32MDd.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol __imp____iob_func
5>libcrypto32MDd.lib(pem_lib.obj) : error LNK2019: unresolved external symbol __imp__fprintf referenced in function _PEM_def_callback
5>libcrypto32MDd.lib(eng_openssl.obj) : error LNK2001: unresolved external symbol __imp__fprintf
5>libcrypto32MDd.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol __imp__fprintf
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertCloseStore@8 referenced in function _capi_find_key
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function _capi_find_cert
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFindCertificateInStore@24 referenced in function _capi_find_cert
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertDuplicateCertificateContext@4 referenced in function _capi_load_ssl_client_cert
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _capi_find_key
5>libcrypto32MDd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertGetCertificateContextProperty@16 referenced in function _capi_cert_get_fname
5>libcrypto32MDd.lib(dso_win32.obj) : error LNK2019: unresolved external symbol __imp__sprintf referenced in function _win32_name_converter
5>E:\Development\SA-MP\samp-discord-connector\build\src\Debug\discord-connector.dll : fatal error LNK1120: 13 unresolved externals
6>------ Build started: Project: ALL_BUILD, Configuration: Debug Win32 ------
6>  Building Custom Rule E:/Development/SA-MP/samp-discord-connector/CMakeLists.txt
6>  CMake does not need to re-run because E:\Development\SA-MP\samp-discord-connector\build\CMakeFiles\generate.stamp is up-to-date.
7>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: PACKAGE, Configuration: Debug Win32 ------
8>Project not selected to build for this solution configuration 
========== Build: 5 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========

 
 
I'm attempting to compile with Visual Studio, version listed is 14.0.25431.01 Update 3 (just installed it yesterday). I have both 32-bit and 64-bit versions of OpenSSL 1.1.0 installed

**Comment by maddinat0r** [comment]
I'm not 100%ly sure what exactly causes this, but I think you can solve this by manually compiling the OpenSSL library with the same compiler you want to compile the plugin with.
