### ISSUE TITLE
I can´t send Messages!

### ISSUE THREAD

**Issue by DarkThinking** [maddinat0r/samp-discord-connector#110]
DCC_SendChannelMessage Dont work!
```
public DCC_OnChannelMessage(DCC_Channel:channel, DCC_User:author, const message[])
{
DCC_SendChannelMessage(channel, "test");
return 1;
}
```

**Comment by kubkodev** [comment]
You're probably still on older version of the plugin. Current signature of callback handling new messages is `DCC_OnMessageCreate(DCC_Message:message);`. However be careful, your code might result in infinite message sending loop, not quite sure what are you trying to achieve there. On 0.3 version it works as expected. Try to post logs and maybe there'll be something what causes message failing to send.

**Comment by DarkThinking** [comment]
> You're probably still on older version of the plugin. Current signature of callback handling new messages is `DCC_OnMessageCreate(DCC_Message:message);`. However be careful, your code might result in infinite message sending loop, not quite sure what are you trying to achieve there. On 0.3 version it works as expected. Try to post logs and maybe there'll be something what causes message failing to send.

Solved, ty

**Comment by ghost** [comment]
> > Probablemente todavía estés usando una versión anterior del complemento. La firma actual de la devolución de llamada que maneja los mensajes nuevos es `DCC_OnMessageCreate(DCC_Message:message);`. Sin embargo, ten cuidado, tu código puede generar un bucle infinito de envío de mensajes; no estoy muy seguro de qué estás intentando lograr allí. En la versión 0.3 funciona como se esperaba. Intenta publicar registros y tal vez haya algo que provoque que el mensaje no se envíe.
> 
> Resuelto, gracias

How did you solve it?

**Comment by ghost** [comment]
> Probablemente todavía estés usando una versión anterior del complemento. La firma actual de la devolución de llamada que maneja los mensajes nuevos es `DCC_OnMessageCreate(DCC_Message:message);`. Sin embargo, ten cuidado, tu código puede generar un bucle infinito de envío de mensajes; no estoy muy seguro de qué estás intentando lograr allí. En la versión 0.3 funciona como se esperaba. Intenta publicar registros y tal vez haya algo que provoque que el mensaje no se envíe.

HELP
Enter an infinite loop
public DCC_OnMessageCreate(DCC_Message:message)
{
    print("ON");

	new content[512];
    new DCC_User:author;
    new authorName[32 + 1];

    DCC_GetMessageContent(message, content);

    DCC_GetMessageAuthor(message, author);
    
    DCC_GetUserName(author, authorName, sizeof(authorName));

 	SendClientMessage(0, -1, "{667aca}[Discord] %s:{ffffff} %s", authorName, content);

    return 1;
}
