### ISSUE TITLE
Add functions related to reactions

### ISSUE THREAD

**Issue by b4ll** [maddinat0r/samp-discord-connector#114]
Is it possible to add functions related to reactions? I mean something like `DCC_CreateReaction`, `DCC_DeleteReaction` or even callback `DCC_OnReactionCreate`.

**Comment by b4ll** [comment]
Well, it's actually possible by using Southclaws' pawn-request plugin. This code works only with custom emoji

```
RequestJSON
(
	RequestsClient("https://discordapp.com/api/channels/"CHANNEL_ID"/messages/"MESSAGE_ID"/reactions/"EMOJI_NAME":"EMOJI_ID"/@me"),
	"",
	HTTP_METHOD_PUT,
	"OnRequestDone",
	.headers = RequestHeaders
	(
		"Authorization", "Bot "BOT_TOKEN
	)
);
```

But I have no idea how to get it working with built in emojis. By the way, callbacks `DCC_OnReactionCreate` and `DCC_OnReactionDelete` would be very useful, I don't think it's possible to do these callbacks with pawn-request plugin.

**Comment by maddinat0r** [comment]
It's definitely possible. You could also create those callbacks via the pawn-requests plugin, as it also supports websockets.
I can't say when I'll add that functionality, but I definitely will at some point in time.
