### ISSUE TITLE
easier building

### ISSUE THREAD

**Issue by maddinat0r** [maddinat0r/samp-discord-connector#115]
Building the plugin is currently really "non-intuitive" (see the AppVeyor config file). I should probably use Conan within CMake for automatically installing all required dependencies.

**Comment by Alasnkz** [comment]
I have merged log-core into discord-connector it self, this solves most of the terrible building experience. Then I added conan to grab most of the packages so now it is just a couple of commands to execute rather than 100 to build discord-connector (especially for debug!).
