### ISSUE TITLE
Question regarding code breaking update

### ISSUE THREAD

**Issue by Chaprnks** [maddinat0r/samp-discord-connector#120]
I read a while ago about the function DCC_OnChannelMessage turning into DCC_OnChannelUpdate. I've finally gotten around to update my script to the latest discord-connector. Most of the script relies heavily on the message[] parameter & I'm not sure how to proceed with obtaining the messages from that callback.

**Comment by maddinat0r** [comment]
`DCC_OnChannelMessage ` was more or less replaced by `DCC_OnMessageCreate`. `DCC_OnMessageCreate` has a `message` parameter, which you can use with all message natives:
```pawn
native DCC_GetMessageId(DCC_Message:message, dest[DCC_ID_SIZE], max_size = DCC_ID_SIZE);
native DCC_GetMessageChannel(DCC_Message:message, &DCC_Channel:channel);
native DCC_GetMessageAuthor(DCC_Message:message, &DCC_User:author);
native DCC_GetMessageContent(DCC_Message:message, dest[], max_size = sizeof dest);
native DCC_IsMessageTts(DCC_Message:message, &bool:is_tts);
native DCC_IsMessageMentioningEveryone(DCC_Message:message, &bool:mentions_everyone);
native DCC_GetMessageUserMentionCount(DCC_Message:message, &mentioned_user_count);
native DCC_GetMessageUserMention(DCC_Message:message, offset, &DCC_User:mentioned_user);
native DCC_GetMessageRoleMentionCount(DCC_Message:message, &mentioned_role_count);
native DCC_GetMessageRoleMention(DCC_Message:message, offset, &DCC_Role:mentioned_role);

native DCC_DeleteMessage(DCC_Message:message);
```
Use `DCC_GetMessageContent` to get the message itself, and `DCC_GetMessageChannel` to get the channel the message was sent in.

**Comment by Chaprnks** [comment]
Great! Thank you for the clarification. I also was wondering, since my script uses "DCC_OnMessageCreate" multiple times, is that function compatible with y_hooks?

**Comment by maddinat0r** [comment]
There should be no reason on why `DCC_OnMessageCreate` won't work with y_hooks, as it's a standard public function. Return values are ignored in that callback, so that wont matter either.

**Comment by Pun1sh3r94** [comment]
```
public DCC_OnMessageCreate(DCC_Message:message)
{
	new DiscordMessage[256];
	DCC_GetMessageContent(message, DiscordMessage);

	new user_name[32 + 1];
	if (!DCC_GetMessageAuthor(message, user_name))
		return 0;

    if (!strcmp(user_name, "Bot", false))
        return 0;
        
	new channel[256];
    if (DCC_GetMessageChannel(message, channel) == 2)//Allow only the #serverchat to write from Discord to Ingame
    {
		new str[145];
		format(str, sizeof str, "{667aca}[Discord] %s:{ffffff} %s", user_name, DiscordMessage);
    	SendClientMessageToAll(-1, str);
	}
    return 1;
}
```

I tried to update it but somehow it gives me everytime 2 Errors, whats wrong with it?

error 035: argument type mismatch (argument 2) for this function ->DCC_GetMessageAuthor
error 035: argument type mismatch (argument 2) for this function ->DCC_GetMessageChannel(message, channel) 

Thanks for reading, hope anyone can help

**Comment by maddinat0r** [comment]
`DCC_GetMessageAuthor` gives a `DCC_User` ID for use with all DCC user natives. Same thing with `DCC_GetMessageChannel` (gives you a `DCC_Channel` ID). Check the include file for what to pass to the functions and all the other user and channel natives.

**Comment by Pun1sh3r94** [comment]
Thanks, finally it works ;P

```
public DCC_OnMessageCreate(DCC_Message:message)
{
	new DiscordMessage[124];
	DCC_GetMessageContent(message, DiscordMessage);

	new DCC_User:user_id;
	DCC_GetMessageAuthor(message, user_id);
	
	new user_name[32+4];
	DCC_GetUserName(user_id, user_name);
       
	new DCC_Channel:channelid;
	DCC_GetMessageChannel(message, channelid);
	
    if(_:channelid == 2 && _:user_id != 1 && _:user_id != 0)//Allow only the #serverchat to write from Discord to Ingame && Ignore UserID 1 because it's our Bot && Invalid User (0 would be Invalid User)
    {
		new str[145];
		format(str, sizeof str, "{667aca}[Discord] %s:{ffffff} %s", user_name, DiscordMessage);
    	SendClientMessageToAll(-1, str);
    	printf("[Discord] %s: %s",user_name, DiscordMessage);
	}
    return 1;
}
```

For everyone who needs a example

**Comment by maddinat0r** [comment]
I would strongly advise against identifying channels and users by the internal plugin ID (e.g. `_:channelid == 2`), as that ID is not bound to the Discord ID's and thus will eventually change between server restarts. You're better off comparing the actual Discord ID's (you can fetch them on the plugin-side through `DCC_GetChannelId`, `DCC_GetUserId`, etc., and on the Discord-side by enabling the developer setting in the app, right-clicking a user or channel, and copying their ID). Discord ID's are unique Snowflake ID's, you can read more in the [Discord Developer docs](https://discordapp.com/developers/docs/reference#snowflakes). Those ID's are represented as strings in the plugin, as they're 64-bit integers and PAWN only has 32-bit cells. Also use `user_id != DCC_INVALID_USER` to check for an invalid user.
