### ISSUE TITLE
Invalid UTF-8 byte

### ISSUE THREAD

**Issue by MassonNN** [maddinat0r/samp-discord-connector#123]
` can't serialize JSON: [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xE3`
`Error while retrieving HTTP POST response from '/api/v6/channels/647060066461286400/messages': end of stream`

code:

```
public OnPlayerConnect(playerid)
{
    
	new string[126], name[MAX_PLAYER_NAME];
	GetPlayerName(playerid, name, MAX_PLAYER_NAME);
	format(string, 126, "Player %s connected!", name);
	DCC_SendChannelMessage(p_Admins, string);
        return 1;
}
```

**Comment by MassonNN** [comment]
this error occurs when characters from other languages are added to the text from the game, for example, Russian, Ukrainian, Polish, etc

moreover, when the text is sent from the discord and processed by this plugin, everything is fine

**Comment by maddinat0r** [comment]
You need to encode the string to UTF-8. [Slice' strlib](https://github.com/oscar-broman/strlib) library for example provides a function to do that.

**Comment by MassonNN** [comment]
![image](https://user-images.githubusercontent.com/35528949/72093173-f5914900-3324-11ea-9f93-efbefec9e263.png)

**Comment by MassonNN** [comment]
as far as I know, in samp, the encoding is cp1251. It is quite strange to do a translation in utf8 from pawn, I think it would be not bad if you did it in the plugin.

**Comment by maddinat0r** [comment]
SA-MP doesn't have a hardcoded encoding, the client and server use the default encoding of the system. cp1251 is the Windows encoding for Cyrillian languages. Adding UTF8 conversion to the plugin will bloat it up by a lot (increase binary size by ~20MB, make building it even more complex), that's why I'm leaving this task to the user.

**Comment by MassonNN** [comment]
Okey. Thanks you for answers and help :)
