### ISSUE TITLE
DCC_AddGuildMemberRole not working or I'm stupid

### ISSUE THREAD

**Issue by mattcomeback** [maddinat0r/samp-discord-connector#124]
So I've been trying to get a discord bot to set a role, and no matter what I do, it will not set period.

Code:
new DCC_Guild:guild_id = DCC_FindGuildById("id here");
new DCC_Role:role_id = DCC_FindRoleById("id here");
new DCC_User:user_id = DCC_FindUserByName(username, discriminator);
DCC_AddGuildMemberRole(guild_id, user_id, role_id);

I've verified my ids are all correct and such and I still can't seem to get it to work, so I'm not sure if I'm missing something or something in Discord's API has changed.  I got it to work one time before.

**Comment by maddinat0r** [comment]
Please check the plugin log file for any errors or warnings.

**Comment by mattcomeback** [comment]
I forgot to mention I’ve done that already, sorry. I also changed the bots username in the discord using the same guild id and all so I know that’s right. Basically everything works but setting a role.

**Comment by maddinat0r** [comment]
Are you using the latest version? If not do so (don't forget to also update the log-core library). Did you maybe disable logging through the `log-config.yml` file? Does this happen for every user and role? Are your bot permissions set correctly?

**Comment by mattcomeback** [comment]
I’m using the latest of both. I don’t use the config file for logcore. I’ve tried different users but not other roles, I’ll give that a shot when I get home from work. The bot permissions are set to Administrator.

**Comment by mattcomeback** [comment]
After trying to try different roles, I still can't get it to set roles.
