### ISSUE TITLE
DCC_AddGuildMemberRole

### ISSUE THREAD

**Issue by tysanio** [maddinat0r/samp-discord-connector#125]
I want to add a role to a member using DC 0.3.2
But i'm stupid about this

my code look like this
` DCC_AddGuildMemberRole(DCC_Guild:560044443114405888, DCC_User:389795801100058627,DCC_Role:670118179066085376);`

I know the 32 integer got a role to id but I don't know how the hell i'm suppose to see it with
`native DCC_Guild:DCC_FindGuildById(const guild_id[]);
or
native DCC_GetGuildId(DCC_Guild:guild, dest[DCC_ID_SIZE], max_size = sizeof dest);`

**Comment by maddinat0r** [comment]
Discord IDs are 64 bit Snowflake IDs. You can't represent them as a number in PAWN, as a PAWN cell in SA:MP is 32 bits in size. You have to fetch Discord plugin objects by ID with functions like `DCC_FindGuildById` and `DCC_FindRoleById`:
```pawn
new DCC_Role:role = DCC_FindRoleById("670118179066085376");
if (role == DCC_INVALID_ROLE)
    return 0; // invalid role id

new DCC_Guild:guild = DCC_FindGuildById("560044443114405888");
if (guild == DCC_INVALID_GUILD)
    return 0; // invalid guild id

new DCC_User:user = DCC_FindUserById("389795801100058627");
if (user == DCC_INVALID_USER)
    return 0; // invalid user id

if (!DCC_AddGuildMemberRole(guild, user, role))
    return 0; // invalid guild, user and/or role passed
```

**Comment by tysanio** [comment]
Thanks you so much! now i'ma little less stupid!

- close -
