### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by D-DeathUser-D** [maddinat0r/samp-discord-connector#128]
Good afternoon, I ran into a problem that the plugin cannot perceive the characters of my language. I would like to know if it is possible to somehow add my own language. Of course, I understand that the bot was not made for a wide audience, but still.

Thanks in advance :)
P.S. Sorry if something is wrong :D

**Comment by maddinat0r** [comment]
Adding that would mean adding UTF-8 detection and conversion directly into the plugin, which is out of scope for it. Refer to issue #123 for more information.
