### ISSUE TITLE
Failed (/lib/libc.so.6: version `GLIBC_2.25' not found (required by plugins/discord-connector.so))

### ISSUE THREAD

**Issue by Rawgamar** [maddinat0r/samp-discord-connector#137]
Working with on issues on a windows server. Linux server when starting server I get
Loading plugin: discord-connector.so
Failed (/lib/libc.so.6: version `GLIBC_2.25' not found (required by plugins/discord-connector.so))

**Comment by maddinat0r** [comment]
Your Linux distribution is too old for the plugin, consider upgrading.
