### ISSUE TITLE
[log-core] server crash detected: fatal signal '6' (SIGABRT) caught

### ISSUE THREAD

**Issue by AmmarSaleemG** [maddinat0r/samp-discord-connector#138]
```
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
[log-core] server crash detected: fatal signal '6' (SIGABRT) caught   
[log-core] fatal signal '6' (SIGABRT) catched  
```
I am using the latest release!
This crash occurred twice when my server hit above 28 players.

**Comment by bluenxyz** [comment]
Yes brother, I am also facing the same problem

**Comment by maddinat0r** [comment]
This is just an information log-core is giving you. It says, that it *detected* a crash (log-core didn't necessarily cause it). You'll have to use crashdetect to find out what plugin actually caused this.
