### ISSUE TITLE
"timeout while initializing data" after updating

### ISSUE THREAD

**Issue by markski1** [maddinat0r/samp-discord-connector#139]
After updating from 0.2.4 to 0.3.2 Discord connector has been giving this error on startup:

```
[08/05/2020 16:58:53]  Loading plugin: discord-connector.so
[08/05/2020 16:59:13]  >> plugin.dc-connector: timeout while initializing data.
[08/05/2020 16:59:13]                          plugin will proceed to retry connecting in the background.
```

No more details than that. The plugin never manages to reconnect at any point during runtime.

I tried generating a new token and trying with it as that's the only thing I could come up with, no changes.

It is worth noting besides updating the plugin, at the same time upgrades were made to the server (debian upgraded from Jessie to Buster, kernel upgraded from 3.9 to 4.19) but I doubt those would cause this issue.

We tried reverting to 0.2.4 but it seems to not like some libraries of the upgraded OS.

Thanks for any help beforehand.

**Comment by markski1** [comment]
Issue was apparently caused by Docker.

**Comment by spacemud** [comment]
Do you remember how you resolved this @markski1? Getting the same issue.

**Comment by VinZ3105** [comment]
> Issue was apparently caused by Docker.
halo , did you remember how to solve this problem?

**Comment by markski1** [comment]
No, but I think it was just using a fresh docker image
