### ISSUE TITLE
Running the linux version

### ISSUE THREAD

**Issue by viruxe** [maddinat0r/samp-discord-connector#14]
I'm currently having this issue: `Failed (/usr/lib/i386-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by plugins/discord-connector.so))`

I've checked and I already have `libstdc++` installed by default. Running Debian 8.7 32bit.

**Comment by maddinat0r** [comment]
Hm, seems like my Ubuntu (I've compiled the Linux build on Ubuntu) uses a slightly newer version of the C++ runtime than Debian Jessie. I'll compile it on Debian and update the download shortly.

**Comment by viruxe** [comment]
I've now also tested it on Debian 7.7 and I get this instead: `Failed (/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/discord-connector.so))`

**Comment by maddinat0r** [comment]
Debian Wheezy is not compatible, because the distributed C++ runtime is too "old" (the plugin needs `GLIBCXX_3.4.20` at least).
I've updated the Linux download. Try it out and please report back if everything works. You'll also need to install the `openssl` package via `apt`.

**Comment by viruxe** [comment]
Worked right out of the box it seems. Thank you very much.

**Comment by maddinat0r** [comment]
You're welcome!
