### ISSUE TITLE
Service not found (-8) running on docker

### ISSUE THREAD

**Issue by dennorske** [maddinat0r/samp-discord-connector#140]
Hello Maddinat0r.
First of all, hands down for making this plugin for the community. It's a great tool to use, and it works pretty well.

I am doing some hosting, and upon facing more and more issues (being the same) I've decided to open up a ticket to give as much info as possible, and for you to solve it.

**Environment;** 
- Docker CE 19.03.8
- Pterodactyl, using docker to separate game servers
- Internal network for pterodactyl (172.18.0.0/24)
- Containers running on Ubuntu 18.04, with a few libs for compatibility with sa-mp servers

**Problem:**
Servers can't get the discord-connector to talk to the gateway (gateway.discord.gg), stating that "Service not found (-8)"

**Possibly related:**
#105 
Possibly Relevant code: https://github.com/maddinat0r/samp-discord-connector/blob/master/src/Http.cpp#L182

Both the servers having issues are currently running on the latest 0.3.2, and it still seems to be a problem that you tried to fix in 0.3.0.

I also think the following 404 is expected, as the gateway is not used as an https endpoint, but here s proof that the container indeed can communicate out to the services. I attached to one of the containers facing this issue
```sh
root@a857005b-cbfa-486c-b655-8abf2d3586a0:~# wget gateway.discord.gg
--2020-05-18 21:20:57--  http://gateway.discord.gg/
Resolving gateway.discord.gg (gateway.discord.gg)... 162.159.133.234, 162.159.134.234, 162.159.135.234, ...
Connecting to gateway.discord.gg (gateway.discord.gg)|162.159.133.234|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gateway.discord.gg/ [following]
--2020-05-18 21:20:57--  https://gateway.discord.gg/
Connecting to gateway.discord.gg (gateway.discord.gg)|162.159.133.234|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-18 21:20:57 ERROR 404: Not Found.

root@a857005b-cbfa-486c-b655-8abf2d3586a0:~# 

```
I also think that the log would state 404 not found, if that was the case. 

Where do you think the problem would be?

**Comment by maddinat0r** [comment]
This issue is already fixed in commit 2d95af805682858a1293c57e6cddf31956efe5d0, but not released yet. Feel free to try the [latest develpoment build](https://ci.appveyor.com/project/maddinat0r/samp-discord-connector/builds/31913914/job/a573k1k0j91150md/artifacts), but be aware that there might be stability issues (especially regarding gateway commands like bot presence and activity status changes).

**Comment by dennorske** [comment]
Thank you @maddinat0r - there seems to be an issue with SSL Certs at this moment using that build.
![image](https://user-images.githubusercontent.com/3287543/82815892-67b09780-9e9a-11ea-91fb-457a1a7758ad.png)

Is this on my side or something missing plugin-side?

**Comment by maddinat0r** [comment]
I did enable certificate validation in that commit I linked above, that's why it's suddenly erroring. Did you install the common CA certificates on your system or in your Docker image? (`apt install ca-certificates` for Debian-based systems)

**Comment by maddinat0r** [comment]
@dennorske I've now completely disabled certificate validation in the latest dev build, as I didn't set it up properly in the first place. Feel free to try the new build here: https://ci.appveyor.com/project/maddinat0r/samp-discord-connector

**Comment by dennorske** [comment]
Thank you for the quick help on this matter. I'll have some people test this out and get back to you :)

**Comment by dennorske** [comment]
Works now, thank you for the quick fix!
