### ISSUE TITLE
CMDs are case sensitive

### ISSUE THREAD

**Issue by Sultan1337** [maddinat0r/samp-discord-connector#143]
I know this isn't an issue but this is rather a suggestion, How do I make CMDs not case sensitive? Also this would've been better if you had accepted my discord request xD (#traxyy#6154)

@maddinat0r

**Comment by Zorono** [comment]
xD he isn't going to accept anyone..
even though, he blocked my Discord Account (idk why...,)

**Comment by Alasnkz** [comment]
Are CMDs even in here? Or are you talking about an external library that adds support. In that case you should ask there.

**Comment by Sultan1337** [comment]
> Are CMDs even in here? Or are you talking about an external library that adds support. In that case you should ask there.

yes those

**Comment by maddinat0r** [comment]
This plugin doesn't have built-in command processing features. You should ask the developer of the command processing library you're using.
