### ISSUE TITLE
[Build sources] Loading plugin: discord-connector Failed

### ISSUE THREAD

**Issue by ByvDeveloper** [maddinat0r/samp-discord-connector#145]
After build introduction according to instructions and push plugin into server (Windows) i'm getting error
![image](https://user-images.githubusercontent.com/49681421/87246868-a86b6c80-c458-11ea-9e86-4d298dc4b4fe.png)

How to solve problem or get more details about it?

Using:
visual studio 2019 (win32 dll build)
cmake 3.18 x32
openssl 0.9.8 x32
log_core 0.5.2

**Comment by Alasnkz** [comment]
log-core2.dll needs to be in the root of the server else the plugin silently fails.

**Comment by ByvDeveloper** [comment]
> log-core2.dll needs to be in the root of the server else the plugin silently fails.

yes, it there. If i'm installing downloaded dll - it works ok. But when i'm self compile sources - plugin silently fails(

**Comment by Alasnkz** [comment]
Make sure you're compiling a release build. The log-core package only ships with a release dll.

**Comment by ByvDeveloper** [comment]
@Alasnkz yes, configuration: Release Win32

**Comment by ByvDeveloper** [comment]
Is it normal, that cl.exe skipped while cmake compiling?
![image](https://user-images.githubusercontent.com/49681421/87706145-b5b18f80-c7a7-11ea-8904-6d79bb4859e6.png)

**Comment by maddinat0r** [comment]
The OpenSSL version you're using is quite old, you should use a recent release. And depending on how you configure the build, the OpenSSL library might be linked dynamically, so you'll also have to copy your OpenSSL DLL's into the SA-MP server folder.

**Comment by ByvDeveloper** [comment]
Yes, it solved problem. Thanks!
