### ISSUE TITLE
Username not showing in game

### ISSUE THREAD

**Issue by FahadTKh** [maddinat0r/samp-discord-connector#156]
The username of discord from channel doesn't show in game. It only shows " on Discord:" 
![image](https://user-images.githubusercontent.com/73723534/97851097-bd754f80-1d16-11eb-8402-055e491f1622.png)

I'm using Centos 7. Any solution for this?

**Comment by FahadTKh** [comment]
> We need code.

This callback in my script and the discord-connector include. Everything works fine except for username not showing in game.
`forward DCC_OnMessageCreate(DCC_Message:message);
public DCC_OnMessageCreate(DCC_Message:message)
{
    new realMsg[100];
    DCC_GetMessageContent(message, realMsg, 100);
    new bool:IsBot;
    new DCC_Channel:channel;
     DCC_GetMessageChannel(message, channel);
    new DCC_User:author;
    DCC_GetMessageAuthor(message, author);
    DCC_IsUserBot(author, IsBot);
    if(channel == g_Discord_Chat && !IsBot) 
    {
        new user_name[32 + 1], str[152];
           DCC_GetUserName(author, user_name, 32);
        format(str,sizeof(str), "%s on Discord: %s",user_name, realMsg);
        SendClientMessageToAll(-1, str);
    }
    return 1;
}`

**Comment by Alasnkz** [comment]
It is working fine for me on the latest development version, I should be releasing a new version later on today so it will work there. But can you provide logs? (logs folder in plugins)

**Comment by FahadTKh** [comment]
Used to work fine for me too, idk stopped working suddenly. Also, logs folder doesn't exist.

**Comment by Alasnkz** [comment]
Oh I think I know why.
You need to go into your discord bot settings and set your server intents:
![image](https://user-images.githubusercontent.com/18373054/97856445-33b48a80-1cf4-11eb-8b93-e6438e47f04f.png)

You need to allow your bot to get user data else it won't be able to!

**Comment by Alasnkz** [comment]
Oh I think I know why.
You need to go into your discord bot settings and set your server intents:
![image](https://user-images.githubusercontent.com/18373054/97856445-33b48a80-1cf4-11eb-8b93-e6438e47f04f.png)

You need to allow your bot to get user data else it won't be able to!

**Comment by FahadTKh** [comment]
Ahahaha hey man thanks. That worked!
