### ISSUE TITLE
Cannot update the embed - invalid embed id '1''

### ISSUE THREAD

**Issue by AlfieBW** [maddinat0r/samp-discord-connector#157]
Iam creating the DCC_CreateEmbed at OnGameModeInit
its great but then i want to edit by using DCC_SetEmbedDescription later in another function but the Embed id does not exist anymore, i get this error:

[10/31/20 17:52:37] [ERROR] DCC_SetEmbedDescription: invalid embed id '1''

**Comment by AlfieBW** [comment]
**The Code**

```
new DCC_Channel:Channel;
#define CHANNEL "00000000000000000000"

public OnGameModeInit()
{
	Embed = DCC_CreateEmbed("TEST TITLE", "**TEST 2**");

	DCC_AddEmbedField(Embed , "Field:", "Field2");

	Channel = DCC_FindChannelById(CHANNEL);
	DCC_SendChannelEmbedMessage(Channel , Embed );
	return 1;
}

public OnPlayerConnect(playerid)
{
	DCC_SetEmbedDescription(Embed , "TEST 3");
	return 1;
}
```

**Comment by Alasnkz** [comment]
DCC_SendChannelEmbedMessage will delete the embed internally. I will probably add a persistent embed option.

**Comment by AlfieBW** [comment]
Its still invalid id even if you try to delete the embed.

**Comment by Alasnkz** [comment]
Because DCC_SendChannelEmbedMessage deletes it.

**Comment by AlfieBW** [comment]
How iam supposed to delete the embed if it deletes after i send it?

**Comment by Alasnkz** [comment]
You don't. Because it deletes it itself.

**Comment by AlfieBW** [comment]
I mean to delete the embed from discord,
I see someone already have done it he is deleting the old embed and sening new one every minute to update players stats.

**Comment by Alasnkz** [comment]
You mean editing? That's in #147

**Comment by AlfieBW** [comment]
Oh so i have to make the message and to delete it as a message.
Can you send me last plugin and inc update becauese i dont have those functions on my build.

**Comment by AlfieBW** [comment]
I see there is already created EditEmbeddedMessage but i dont have those natives on my inc and plugin

**Comment by AlfieBW** [comment]
Any reply?
