### ISSUE TITLE
Can't get any member info

### ISSUE THREAD

**Issue by mikescnr** [maddinat0r/samp-discord-connector#159]
For some reason all the functions to get information about a member have stopped working...

```
public DCC_OnMessageCreate(DCC_Message:message)
{
	new DCC_User:author;
	DCC_GetMessageAuthor(message, author);
	new szUserID[DCC_ID_SIZE];
	DCC_GetUserId(author, szUserID);

	new authorName[32 + 1];
	DCC_GetGuildMemberNickname(DiscordGuild_MCNR, author, authorName);
	if(isnull(authorName)) DCC_GetUserName(author, authorName);

	printf("Message ID %i created. Author ID %i (%s), nick '%s'", _:message, _:author, szUserID, authorName);

	return 1;
}
```

It's not getting the info at all:
> Message ID 1 created. Author ID 0 (), nick ''

On the latest version. And I think it may have started happening on the old version too. I have tried removing and re-authorising the bot (I have 2 bots a public and dev one and they both have the same issue). Anything else I should try?

@Alasnkz excited to try the embedding feature when I can, if I can get this stuff fixed, good work.

**Comment by mikescnr** [comment]
Tried generating a new token and making sure the bot had full perms too..

**Comment by Alasnkz** [comment]
Set your server intents in your discord bot settings, this is a recent discord change.

The next version will specifically tell you (and refuse to connect due to new discord api) if you don't do this
