### ISSUE TITLE
[Error] libssl.so.10

### ISSUE THREAD

**Issue by AlaDyn172** [maddinat0r/samp-discord-connector#16]
Hello,
I have this error when starting server:
[23:36:26]  Loading plugin: discord-connector.so
[23:36:26]   Failed (libssl.so.10: cannot open shared object file: No such file or directory)

**Comment by viruxe** [comment]
You have to install OpenSSL, most likely.

**Comment by AlaDyn172** [comment]
After 'apt-get install openssl', still same error.

**Comment by AlaDyn172** [comment]
Can someone help me, pls?

**Comment by maddinat0r** [comment]
Which distribution are you using (name and version)? Try installing the 32bit package:
```sh
apt install openssl.i386
```

**Comment by AlaDyn172** [comment]
Debian 7.11 x64

**Comment by viruxe** [comment]
How did you fix this issue?

**Comment by AlaDyn172** [comment]
I didn't fix on Debian.
Just install Ubuntu ;)

**Comment by Southclaws** [comment]
I should say I've also replaced debian with ubuntu recently because I kept having outdated libraries and software issues with debian 8.
