### ISSUE TITLE
Problem About UTF-8

### ISSUE THREAD

**Issue by kutayakkaya** [maddinat0r/samp-discord-connector#167]
Can you please fix this UTF-8 problem?

`[plugins/discord-connector] can't serialize JSON: [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xFD`

Characters:

`ğğ ĞĞ çç CC ıı II ii İİ öö ÖÖ ŞŞ şş üü ÜÜ`

**Comment by Alasnkz** [comment]
script that causes the issue?

**Comment by kutayakkaya** [comment]
> script that causes the issue?

Unfortunately it looks like that.

`DCC_CreateEmbed("Title", params, "", "", 0);`

When `params` contains a Turkish character, script gives an error message.

**Comment by kutayakkaya** [comment]
> script that causes the issue?

Unfortunately it looks like that.

`DCC_CreateEmbed("Title", params);`

When `params` contains a Turkish character, script gives an error message.

**Comment by kutayakkaya** [comment]
I solved the problem by doing UTF-8 encode to the string.
