### ISSUE TITLE
Permission Intent

### ISSUE THREAD

**Issue by kylesmith0** [maddinat0r/samp-discord-connector#169]
Hi,

On version 0.3.1 the plugin loads fine however after 0.3.1 there is an issue with intent permissions.

I've granted the bot admin permissions as a whole, no luck and also done permissions individually, no luck either.

Any suggestions please?

**Comment by Alasnkz** [comment]
Intent permissions are configured in the bot settings, not your server permission settings.

**Comment by kylesmith0** [comment]
> Intent permissions are configured in the bot settings, not your server permission settings.

I already went to the discord developer settings and changed them from there, selected the permissions, copied the link and attached the bot to the channel, same issue.

Why does it not happen on previous discord versions but only after 0.3.1

**Comment by Alasnkz** [comment]
It is a discord change, nothing will work with the bot if intents are set, hence why I added it as a mandatory thing to prevent issues here. 

![image](https://user-images.githubusercontent.com/18373054/99885551-98953d80-2c2d-11eb-8fed-e29c358affe1.png)

This is what you need.

**Comment by kylesmith0** [comment]
Thank you.
