### ISSUE TITLE
Discord Plugin is causing lag / using all the CPU!

### ISSUE THREAD

**Issue by AlfieBW** [maddinat0r/samp-discord-connector#173]
After the update of discord this plugin is causing only lag and using all the cpu for no reason.
Please take a look what is happening, this is happening to other server owners too who are using this plugin.

Thank you!

**Comment by Alasnkz** [comment]
I would need proof of this. People are fine with the update (it has been out for 2 months almost...). Is this your host blaming this plugin?

**Comment by traxyy** [comment]
I'm also facing this problem!!

**Comment by AlfieBW** [comment]
I mean about the discord update 2 3 days ago (this started 2 days ago)
And as you see theres someone else here too with that problem.

**Comment by Alasnkz** [comment]
That person was a troll. Also a discord update (which is mostly for the client - not the api) wouldn't cause such thing.

**Comment by AlfieBW** [comment]
I will take more informations and will send here.

Is the host who reported me which plugin was causing high cpu and i disabled it and it just went normal.

**Comment by AlfieBW** [comment]
Alasnkz i think i found something.
As the tests i made high cpu usage happen when i create any new folder on the main directory while the server is running.  (Linux server not sure in windows)

Please give it a try, if this is still nosense to you then i will close this issue.
