### ISSUE TITLE
Failed to load, no explicit errors

### ISSUE THREAD

**Issue by markski1** [maddinat0r/samp-discord-connector#182]
Discord connector fails to load on server init, on Windows 10 x64. All it does is say "Failed", with no further or more precise error messages.

Load order: `plugins crashdetect mysql streamer pawnraknet samp-precise-timers discord-connector samp_bcrypt ColAndreas nativechecker`

![imagen](https://user-images.githubusercontent.com/22557859/109390329-c5718480-78ef-11eb-88d4-e896f3e4ce05.png)

Tried versions 0.3.2 and 0.3.5

**Comment by markski1** [comment]
In good "ask for help and keep trying" fashion, I found the issue immediatly. I was missing log-core2, as I thought it used the same log-core as MySQL.

Having found this, I'd like to change the intent of this issue to making plugin load errors give a more explicit message on why it failed

**Comment by Alasnkz** [comment]
don't think this is possible
