### ISSUE TITLE
?

### ISSUE THREAD

**Issue by BrianxDev** [maddinat0r/samp-discord-connector#209]
CMake Error at libs/cmake-conan/conan.cmake:82 (message):
  Please specify in command line CMAKE_BUILD_TYPE
  (-DCMAKE_BUILD_TYPE=Release)
Call Stack (most recent call first):
  libs/cmake-conan/conan.cmake:544 (conan_cmake_settings)
  CMakeLists.txt:83 (conan_cmake_run)

**Comment by Kahler25** [comment]
Use `cmake -DCMAKE_BUILD_TYPE=Release ..` and it's done.
