### ISSUE TITLE
sending messages from one channel

### ISSUE THREAD

**Issue by IGNick** [maddinat0r/samp-discord-connector#21]
i have my bots in many channels and i wanted it to send messages from one channel but this doesnt work. Is there a way to do that?

`public DCC_OnChannelMessage(DCC_Channel:channel, const author[], const message[])
{
	if(channel == 388423556721672192)
	{
	new str[145];
	format(str, sizeof str, "[Discord/%s] %s: %s", channel_name, author, message);
	SendClientMessageToAll(-1, str);
	}
	return 1;
}`

**Comment by maddinat0r** [comment]
You can't do `if(channel == 388423556721672192)`, because `channel` has an internal value assigned, not the actual Discord channel ID. You need to use `DCC_GetChannelId` to retrieve the actual Discord ID.
