### ISSUE TITLE
open.mp support

### ISSUE THREAD

**Issue by xPaulFTW** [maddinat0r/samp-discord-connector#218]
Hi. On open.mp server.cfg is replaced by config.json and samp-discord-connector is not checking the config.josn and i can't define the discord_bot_token

**Comment by kledsonzg** [comment]
Working well here:
![](https://imgur.com/wovBitF.jpg)
![](https://imgur.com/lcOuO3z.jpg)
![](https://imgur.com/E2tmJlK.jpg)

server.cfg remains in the folder:
![](https://imgur.com/KZ3cpf7.jpg)

**Comment by xPaulFTW** [comment]
You use server.cfg, I use config.json
