### ISSUE TITLE
Connection Crashes on Startup

### ISSUE THREAD

**Issue by Faskis** [maddinat0r/samp-discord-connector#22]
Since the latest update with Discord which adds categories to servers, our bot seems to crash on DCC_Connect. These are the only logs that display from the plugin (it's repeated every couple of seconds):

> [10/09/2017 12:58:52] [INFO] changed log level from 'warning, error' to 'debug, info, warning, error'
>[10/09/2017 12:58:58] [DEBUG] DCC_Connect("*****")
>[10/09/2017 12:58:58] [DEBUG] CCallback::Create(amx=0xaef4ad8, name='DCC_OnChannelMessage')
>[10/09/2017 12:58:58] [DEBUG] CCallback::Create - callback index for 'DCC_OnChannelMessage': 259
>[10/09/2017 12:58:58] [INFO] Callback 'DCC_OnChannelMessage' set up for delayed execution.
>[10/09/2017 12:58:58] [DEBUG] CNetwork::Initialize
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpConnect
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpGet
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpSendRequest
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpPrepareRequest
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpSendRequest(/api/v5/gateway) (actual send)
>[10/09/2017 12:58:58] [DEBUG] CNetwork::HttpWriteRequest
>[10/09/2017 12:58:58] [DEBUG] CNetwork::WsConnect
>[10/09/2017 12:58:58] [DEBUG] CNetwork::WsRead
>[10/09/2017 12:58:58] [DEBUG] CNetwork::WsIdentify
>[10/09/2017 12:58:58] [DEBUG] CNetwork::OnWsRead
>[10/09/2017 12:58:58] [DEBUG] OnWsRead: {
>[10/09/2017 12:58:58] [DEBUG] CNetwork::DoHeartbeat
>[10/09/2017 12:58:58] [DEBUG] sending heartbeat
>[10/09/2017 12:58:58] [DEBUG] CNetwork::WsRead
>[10/09/2017 12:58:59] [DEBUG] CNetwork::OnWsRead
>[10/09/2017 12:58:59] [DEBUG] OnWsRead: {
>[10/09/2017 12:58:59] [DEBUG] heartbeat ACK
>[10/09/2017 12:58:59] [DEBUG] CNetwork::WsRead
>[10/09/2017 12:58:59] [DEBUG] CNetwork::OnWsRead
>[10/09/2017 12:58:59] [DEBUG] OnWsRead: {
>[10/09/2017 12:58:59] [DEBUG] CNetwork::WsRead
>[10/09/2017 12:58:59] [DEBUG] CNetwork::OnWsRead
>[10/09/2017 12:58:59] [DEBUG] OnWsRead: {

**Comment by maddinat0r** [comment]
There is a new version coming soon, which should improve a lot of things, especially stability and connection reliability.
I'll leave this issue open for now, and will mention you here when I'll release that new version, so you can try it out and check if it's fixed for you.

**Comment by maddinat0r** [comment]
@Faskis v0.2 is out now, please try it out.
