### ISSUE TITLE
Message reply

### ISSUE THREAD

**Issue by EOussama** [maddinat0r/samp-discord-connector#223]
Hi.

It would be awesome to have the ability to reply to an existing message.
![image](https://user-images.githubusercontent.com/22644543/180835592-a905b032-f872-45e5-a74c-119c1feab1c9.png)

**Comment by Alasnkz** [comment]
This is a slash command feature. (0.3.6)
![image](https://user-images.githubusercontent.com/18373054/183869590-2c187372-c179-42ac-88f5-5aadef1a2d0a.png)

**Comment by EOussama** [comment]
How do you achieve that?

**Comment by AtlanticCityRoleplay** [comment]
> This is a slash command feature. (0.3.6)
> ![image](https://user-images.githubusercontent.com/18373054/183869590-2c187372-c179-42ac-88f5-5aadef1a2d0a.png)
> 

What Happens to 0.3.6 Release...?

Will it be released soon....

**Comment by Alasnkz** [comment]
Yes. Shortly. Like... maybe a few hours?

**Comment by AtlanticCityRoleplay** [comment]
> Yes. Shortly. Like... maybe a few hours?

Thanks for the the Quick Response, 💝, Inspired by the work in your Age...
