### ISSUE TITLE
I cant fix this error even i compiled with right include and also using right plugins

### ISSUE THREAD

**Issue by AwayTitan** [maddinat0r/samp-discord-connector#226]
I cant fix this error even i compiled with right include and also using right plugins
This is error 
Loading filterscript 'DChat.amx'... 
Error: Function not registered: 'DCC_FindChannelById' 
Error: Function not registered: 'DCC_GetMessageContent' 
Error: Function not registered: 'DCC_GetMessageChannel' 
Error: Function not registered: 'DCC_GetMessageAuthor' 
Error: Function not registered: 'DCC_IsUserBot'  Error: Function not registered: 'DCC_GetUserName' 
 Error: Function not registered: 'DCC_SendChannelMessage'

**Comment by AtlanticCityRoleplay** [comment]
> I cant fix this error even i compiled with right include and also using right plugins
> This is error 
> Loading filterscript 'DChat.amx'... 
> Error: Function not registered: 'DCC_FindChannelById' 
> Error: Function not registered: 'DCC_GetMessageContent' 
> Error: Function not registered: 'DCC_GetMessageChannel' 
> Error: Function not registered: 'DCC_GetMessageAuthor' 
> Error: Function not registered: 'DCC_IsUserBot'  Error: Function not registered: 'DCC_GetUserName' 
>  Error: Function not registered: 'DCC_SendChannelMessage' 
> 

Check the Server.cfg, Plugin not yet Loaded
