### ISSUE TITLE
Can't load discord-connector.so CentOs 7

### ISSUE THREAD

**Issue by gurmani11** [maddinat0r/samp-discord-connector#23]
First i loaded discord connector in Windows 10. it worked very well.
After that when i tried to connect it on CentOs 7, i received this error.
`Loading plugin: discord-connector.so
Failed (libssl.so.1.0.0: cannot open shared object file: No such file or directory)`
I searched over the internet for solution and found nothing (To be honest, i am just learning to use VPS)(Sorry for inconvenience)
What do i do to resolve it?
do i need to install Debian 8, to resolve this problem?
do i need to make some directory in lib folder?

**Comment by maddinat0r** [comment]
Try this:
```sh
yum install openssl-libs.i686
```

**Comment by gurmani11** [comment]
Its already installed
`Package 1:openssl-libs-1.0.2k-8.el7.i686 already installed and latest version
Nothing to do
`

**Comment by maddinat0r** [comment]
Seems like CentOS 7 updated the libssl package from 1.0.0 to 1.0.2.
I've compiled v0.2 with the newest libssl package, so you should try out that version.

**Comment by gurmani11** [comment]
Thank you it works

**Comment by maddinat0r** [comment]
You're welcome.
