### ISSUE TITLE
Discord embed message

### ISSUE THREAD

**Issue by marcelog09** [maddinat0r/samp-discord-connector#235]
Just out of nowhere embed messages stopped being sent and no errors in the log. Anyone else having this problem?

**Comment by AbdulOmarCR** [comment]
I'm having it.

**Comment by AtlanticCityRoleplay** [comment]
> Just out of nowhere embed messages stopped being sent and no errors in the log. Anyone else having this problem?

I am having too....

**Comment by marcelog09** [comment]
Apparently it's working again (?)
