### ISSUE TITLE
Bot Unable to Send message in Embed Format

### ISSUE THREAD

**Issue by AtlanticCityRoleplay** [maddinat0r/samp-discord-connector#236]
[ERROR] Error while retrieving HTTP POST response from '/api/v8/channels/1...4/typing': end of stream

**Comment by AbdulOmarCR** [comment]
Hi, yes, I'm getting the same error right now.

**Comment by AtlanticCityRoleplay** [comment]
> Hi, yes, I'm getting the same error right now.

I think Discord has made some changes in their API, I think So..

**Comment by marcelog09** [comment]
> > Hi, yes, I'm getting the same error right now.
> 
> I think Discord has made some changes in their API, I think So..

Apparently it's working again (?)

**Comment by AbdulOmarCR** [comment]
Yeah it's working again idk why

**Comment by AtlanticCityRoleplay** [comment]
> > > Hi, yes, I'm getting the same error right now.
> > 
> > I think Discord has made some changes in their API, I think So..
> 
> Apparently it's working again (?)

For me it's still can't Message... 😢

**Comment by AtlanticCityRoleplay** [comment]
> Yeah it's working again idk why

Did you Restarted your server or did something.?

**Comment by marcelog09** [comment]
> 
stopped working again...

**Comment by AtlanticCityRoleplay** [comment]
> > 
> stopped working again...
> 

😢🥲
