### ISSUE TITLE
Unable to Load Plugin in Pre Release

### ISSUE THREAD

**Issue by AtlanticCityRoleplay** [maddinat0r/samp-discord-connector#238]
Failed (/lib/i386-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by plugins/discord-connector.so))

..? @Alasnkz

**Comment by Alasnkz** [comment]
I replaced the Linux download, could you try again?

**Comment by AtlanticCityRoleplay** [comment]
> I replaced the Linux download, could you try again?

I will try at Morning...💝

**Comment by AtlanticCityRoleplay** [comment]
Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by plugins/discord-connector.so))

@Alasnkz 

Still Failed to Load...

**Comment by NicKv7** [comment]
i also have the same problem.
Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by plugins/discord-connector.so))

something to solve or the plugin will be recompiled?

**Comment by AtlanticCityRoleplay** [comment]
> i also have the same problem.
> Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by plugins/discord-connector.so))
> 
> something to solve or the plugin will be recompiled?

It not yet fixed..

**Comment by AtlanticCityRoleplay** [comment]
@Alasnkz 

Any Updates regards this issue..?

Still i can't run plug-in (0.3.6)

Using (0.3.5) instead...

**Comment by Alasnkz** [comment]
What's your exact operating system? You must be running a very old one, which is very hard to support with modern tooling nowadays.

**Comment by AtlanticCityRoleplay** [comment]
> What's your exact operating system? You must be running a very old one, which is very hard to support with modern tooling nowadays.

It was a Host Provider,

www.lemehost.com

**Comment by Alasnkz** [comment]
Well, I'm updating DCC again and I might have an idea of what to do to lower the GLIBC requirement again. I'll let you know when I've updated the download again.

**Comment by AtlanticCityRoleplay** [comment]
> Well, I'm updating DCC again and I might have an idea of what to do to lower the GLIBC requirement again. I'll let you know when I've updated the download again.

Thank you 💖

**Comment by Alasnkz** [comment]
I updated it again. Try now.

**Comment by NicKv7** [comment]
Loading component discord-connector.so
        Successfully loaded component discord-connector (0.3.6.1) with UID 493dfe4f6ea1841f

OK

**Comment by NicKv7** [comment]
[19:02:29]  Loading plugin: discord-connector.so
[19:02:29]  >> discord-connector: Usage of environmental variable SAMP_DISCORD_BOT_TOKEN is deprecated for DCC_BOT_TOKEN
[19:02:29]  >> discord-connector: This environmental variable will be removed in a later release.
[19:02:29]  >> discord-connector: bot token not specified in environment variable or server config.
[19:02:29]   Failed.


after all, which variable needs to be defined in server.cfg for the plugin to work? I tested it in openmp and the settings in config.json were ok.
when I test on the sa-mp server I have these errors, even redefining the variables

discord_bot_token
dcc_bot_token
samp_discord_bot_token

**Comment by Alasnkz** [comment]
Ignore the `SAMP_DISCORD_BOT_TOKEN` message, forgot to actually check if it is in use.
discord_bot_token should be for server.cfg.

**Comment by NicKv7** [comment]
samp server
discord_bot_token defined
v0.3.5
[19:08:14]  Loading plugin: discord-connector.so
[19:08:14]  >> plugin.dc-connector: v0.3.5 successfully loaded.
[19:08:14]   Loaded.
v0.3.6
[19:09:40]  Loading plugin: discord-connector.so
[19:09:40]  >> discord-connector: Usage of environmental variable SAMP_DISCORD_BOT_TOKEN is deprecated for DCC_BOT_TOKEN
[19:09:40]  >> discord-connector: This environmental variable will be removed in a later release.
[19:09:40]  >> discord-connector: bot token not specified in environment variable or server config.
[19:09:40]   Failed.

**Comment by Alasnkz** [comment]
Oh I see where I went wrong. It'll be fixed soon.

**Comment by AtlanticCityRoleplay** [comment]
> Should be fixed now.

Plugin Loaded Successful and Working Good...
