### ISSUE TITLE
Messages are not send to channel

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [maddinat0r/samp-discord-connector#24]
Hey,

I just tried working with Discord plugin, I am facing a problem of; The messages of players are being send to the channel but the messages called by server are not. I am using same function for both. 

Here's the function 
`public Discord_SendMessage(string[])
{
	printf("[Discord_SendMessage] %s",string);
	DCC_SendChannelMessage(Discord_EchoC, string);
	return 1;
}`

This is being called in a different script from my main script.

In my server log

> [Discord_SendMessage] • Zombies has won the zombie apocalypse! Reward: $10000
> [18:13:57]
>  [Discord_SendMessage] • [RANDOM] Next Mission is Team-deathmatch: Odd Little Town. | Map by JimmySpaceTravel1337.
> [18:14:15]
>  [Discord_SendMessage] • Mission Team-deathmatch: Odd Little Town has successfully initialized.

While This was sent from log

>  [Discord_SendMessage] Sasuke_Uchiha (0):1 test

This looks pretty odd as it's the same thing so why won't it send those messages?

[discord-connector-log.txt](https://github.com/maddinat0r/samp-discord-connector/files/1315030/discord-connector-log.txt)

**Comment by maddinat0r** [comment]
Can you try out v0.2 please?

**Comment by Sasuke-Uchiha** [comment]
Sure i will check and report back soon.

**Comment by Sasuke-Uchiha** [comment]
So I just checked and it was same, I noticed that the problem exists only to those messages which have '•' in it. So I used script to find this and remove it from script and it works now. 

`new keymsg=strfind(string, "•", true);
	if(keymsg != -1) strdel(string, keymsg, keymsg+1);`

Used this and it worked.

**Comment by maddinat0r** [comment]
Ah, you're experiencing an already known bug, which still exists in v0.2. Special (non-ANSI) symbols aren't processed correctly. I'll close this issue and link it to #27, since they're the same. You can subscribe to that issue if you want to get notified on any progress.
