### ISSUE TITLE
Problems in 0.3.6 [Linux]

### ISSUE THREAD

**Issue by AtlanticCityRoleplay** [maddinat0r/samp-discord-connector#240]
1. **Unable to Send Embed Message in PM**

2 . **Embed Message with Thumbnail is not Sending to Discord**

>Error Message: " Can't write to Discord websocket gateway: Operation canceled (125) "

3. **Some Unknown Error**

>Error Message: " Unknown gateway event 'GUILD_AUDIT_LOG_ENTRY_CREATE' "

I exactly Don't Know is this Bug or Happening Only in My server..?

**Comment by Alasnkz** [comment]
Embed thumbnail should be fixed now.

**Comment by AtlanticCityRoleplay** [comment]
Thank You ✨
