### ISSUE TITLE
libssl.so.1.0.0

### ISSUE THREAD

**Issue by Mielnik** [maddinat0r/samp-discord-connector#25]
[04:34:01]  Loading plugin: discord-connector.so
[04:34:01]   Failed (libssl.so.1.0.0: cannot open shared object file: No such file or directory)

I used:
sudo apt-get update
sudo apt-get install libssl1.0.0 libssl-dev

The error still exists.
I have a linux distribution debian 7.

**Comment by maddinat0r** [comment]
You need to install the 32bit libssl package:
```sudo apt-get install libssl1.0.0:i386```
Unfortunately this won't bring you any further anymore, since v0.2 is now released and I couldn't compile the plugin on Debian Jessie due to broken package dependencies, which means that you can't upgrade to v0.2 yet.
