### ISSUE TITLE
How to get a maximum arrays in GetUserName

### ISSUE THREAD

**Issue by KirovNoName** [maddinat0r/samp-discord-connector#251]
is this correct?

        new dcname[DCC_ID_SIZE];
        DCC_GetUserName(user, dcname, 16);

**Comment by AtlanticCityRoleplay** [comment]
> is this correct?
> 
>         new dcname[DCC_ID_SIZE];
>         DCC_GetUserName(user, dcname, 16);
> 
> 
> 

Wrong,

For Getting User name

```
new dcname[DCC_USERNAME_SIZE];
DCC_GetUserName(user, dcname, sizeof(dcname));

```

**Comment by fxprima** [comment]
This should work : 
```
new dcname [DCC_USERNAME_SIZE];
DCC_GetUserName(user, dcname);
```

**Comment by KirovNoName** [comment]
thanks
