### ISSUE TITLE
new usernames issue

### ISSUE THREAD

**Issue by ihaswn** [maddinat0r/samp-discord-connector#257]
since discord is envolving and updating the usernames (https://support.discord.com/hc/en-us/articles/12620128861463-New-Usernames-Display-Names#h_01GXPQAGG6W477HSC5SR053QG1), the old username#id is not going to work, and with that this plugin wont work, the DCC_FindUserByName is not going to work and i no longer can find a user by its name#id.

since username is not fully updated and is activating for everybody one by one, i suggest to update DCC_FindUserByName, if i need to get client by a new username set the second param to a empty string ("") so both username types still be accessable

**Comment by marcelog09** [comment]
+UP

**Comment by sunkie25** [comment]
+1, In my case the ID is 0 for every username. https://i.imgur.com/PEPZYXx.png

**Comment by iMarkeh18** [comment]
up

**Comment by ihaswn** [comment]
fix: you can use #0 for new usernames, like username#0
