### ISSUE TITLE
DCC_OnChannelMessage callback author parameter proplem

### ISSUE THREAD

**Issue by JohnMagdy** [maddinat0r/samp-discord-connector#26]
Hello everybody, so  iam facing some proplems with **_DCC_OnChannelMessage_** callback's **_author_** parameter after upgrading to v0.2 
for example: 
```
public DCC_OnChannelMessage(DCC_Channel:channel, DCC_User:author, const message[])
{
   if(DCC_IsUserBot(author, true)) return 0; // (24480) : error 035: argument type mismatch (argument 2)
   CallLocalFunction("OnDiscordMessage", "s", author); // (24506) : warning 213: tag mismatch
   return 1;
}
```

1. please some help on fixing those errors/warnings, it 'd be great to fix those parameters proplem 
2. really i need linux build for v0.2 (it 'd be great if its compitable with/or built in Centos 7.x for example Centos 7.3 because of libssl.so.1.0.0 missing......proplem) please
3.  i have a suggestion, it 'd be great to see a function which checks if spefied channel is valid 
for example: ```if(DCC_IsChannelValid("general")) {}``` 
Syntax: ```native DCC_IsChannelValid(channel[]);```
4. it 'd be great to update Discord Connector Plugin's main thread's example code so we might understand how your new functions/callbacks works

**Comment by maddinat0r** [comment]
You're not calling the native correctly. Here's how you do it:
```pawn
public DCC_OnChannelMessage(DCC_Channel:channel, DCC_User:author, const message[])
{
	new bool:is_bot;
	if (!DCC_IsUserBot(author, is_bot))
		return 0; //invalid user
		
	if(is_bot)
		return 0;
	
	new user_name[33];
	DCC_GetUserName(author, user_name);
	CallLocalFunction("OnDiscordMessage", "s", user_name); // (24506) : warning 213: tag mismatch
	return 1;
}
```
