### ISSUE TITLE
I Have An This Issue With Discord Connector Let Some One Help Me To Solve

### ISSUE THREAD

**Issue by Rockstar-Dev-Tamil** [maddinat0r/samp-discord-connector#275]
Hey Guys.. 

I Am Rockstar The Developer Of Legendary RolePlay.. 
When I Tried To Put Discord Connector To My SERVER it Shows This Error

 Failed (plugins/discord-connector: cannot open shared object file: No such file or directory)

Let some one help me to solve

**Comment by Zakorya** [comment]
You add plugin discord-connector to serve.cg?

**Comment by AtlanticCityRoleplay** [comment]
> Hey Guys..
> 
> I Am Rockstar The Developer Of Legendary RolePlay.. When I Tried To Put Discord Connector To My SERVER it Shows This Error
> 
> Failed (plugins/discord-connector: cannot open shared object file: No such file or directory)
> 
> Let some one help me to solve

You haven't placed the log_core in root folder as discord connector uses log core to store logs

**Comment by Rockstar-Dev-Tamil** [comment]
> > Hey Guys..
> > I Am Rockstar The Developer Of Legendary RolePlay.. When I Tried To Put Discord Connector To My SERVER it Shows This Error
> > Failed (plugins/discord-connector: cannot open shared object file: No such file or directory)
> > Let some one help me to solve
> 
> You haven't placed the log_core in root folder as discord connector uses log core to store logs

Bro The Bot Turns On But It Automatically Turns Off When I Check Server_Log It's Shows Timeout While Initializing

**Comment by karthigenius** [comment]
> > > Hey Guys..
> > > I Am Rockstar The Developer Of Legendary RolePlay.. When I Tried To Put Discord Connector To My SERVER it Shows This Error
> > > Failed (plugins/discord-connector: cannot open shared object file: No such file or directory)
> > > Let some one help me to solve
> > 
> > 
> > You haven't placed the log_core in root folder as discord connector uses log core to store logs
> 
> Bro The Bot Turns On But It Automatically Turns Off When I Check Server_Log It's Shows Timeout While Initializing

Try Using the Stable Release 0.3.5 instead of Pre Release, It may Break.

**Comment by Rockstar-Dev-Tamil** [comment]
> > > > Hey Guys..
> > > > I Am Rockstar The Developer Of Legendary RolePlay.. When I Tried To Put Discord Connector To My SERVER it Shows This Error
> > > > Failed (plugins/discord-connector: cannot open shared object file: No such file or directory)
> > > > Let some one help me to solve
> > > 
> > > 
> > > You haven't placed the log_core in root folder as discord connector uses log core to store logs
> > 
> > 
> > Bro The Bot Turns On But It Automatically Turns Off When I Check Server_Log It's Shows Timeout While Initializing
> 
> Try Using the Stable Release 0.3.5 instead of Pre Release, It may Break.

Thanks Bro I Fixed That Problem Bro I
