### ISSUE TITLE
Messages isn't being received/sent && errors/warnings

### ISSUE THREAD

**Issue by JohnMagdy** [maddinat0r/samp-discord-connector#28]
Hello everybody, please sir iam facing some proplems after upgrading to v2.0 as i can't receive any messages from my sa-mp server or sent any messages to my sa-mp server and i have detected some errors/warnings on my server dirctory/logs/*

please some help sir 
[Discord-v2.0-logs.zip](https://github.com/maddinat0r/samp-discord-connector/files/1327365/Discord-v2.0-logs.zip)

**Comment by maddinat0r** [comment]
Does this always happen some hours after server start? Or do you now constantly get these errors, even directly after starting your server?

**Comment by JohnMagdy** [comment]
after some minutes of server start but after start start it works for some minutes and then it get bugged and won't work even untill i restart my server again

**Comment by maddinat0r** [comment]
This might be an issue with your bot. Are you sure your bot token is correct and your bot is not banned/blocked from Discord?

**Comment by JohnMagdy** [comment]
found an issue on my token it was changed and i didn't update it on my script but after updating it on my script the same proplem didn't get fixed as my Discord BOT isn't Banned/Blocked and its online but i can't receive any message from my samp server or send any message to my sa-mp server and my discord bot is online on my online list on my discord server 
[Discord-v2.0-Logs.zip](https://github.com/maddinat0r/samp-discord-connector/files/1327787/Discord-v2.0-Logs.zip)

**Comment by maddinat0r** [comment]
Your bot token is still invalid, as seen by this repeating log message:
```
[ERROR] Discord terminated websocket connection; reason: Authentication failed. (4004)
```

**Comment by maddinat0r** [comment]
Seems like you've also sent me some old log entries along the case. Yes, your bot token seems correct.
For some reason the HTTP request seems to fail. Your issue is partly related to #29, so there's not much I can do for now until I fix that and add some more debug logs.
I'll try to reproduce this, as it seems to happen after some hours of no HTTP activity.

**Comment by Evocator** [comment]
Not sure if my issue is related to this and to #29, but DCC_SendChannelMessage stops responding after a couple of minutes when the server launches.
Here is the log: https://pastebin.com/raw/FJUnNH42

**Comment by maddinat0r** [comment]
You're not the first one reporting this, there's definitely a problem with the plugin, and I'm starting to think that this is not related to #29. I'll definitely take a closer look at this.

**Comment by maddinat0r** [comment]
@JohnMagdy @Evocator Could you please try out v0.2.1 and report back with your results here?
