### ISSUE TITLE
Support Polish symbols

### ISSUE THREAD

**Issue by criticalerror99** [maddinat0r/samp-discord-connector#30]
Messages with Polish symbols (ą, ę, ó, ć, ł, ż, ź) are not sending on Discord.

**Comment by Southclaws** [comment]
Are you sending these characters from SA:MP? This is an ANSI issue, there should be (maybe there is?) a way to declare what codepage your server's users use so the plugin can perform a proper transformation decode to Unicode so it can be rendered properly on the Discord client. And vice versa, so when Unicode is decoded from the Discord API, it can be transformed into the correct codepage for the server.

**Comment by criticalerror99** [comment]
OK. I converted polish symbols to ANSI format in Notepad++ and created function to replace these symbols in string. It works, thanks for help.

**Comment by maddinat0r** [comment]
This is still a thing the plugin should be doing, not the user.
I'll link this to #27 since it's basically the same thing.
