### ISSUE TITLE
cmake and make can't find boost libraries

### ISSUE THREAD

**Issue by juanpenia** [maddinat0r/samp-discord-connector#32]
I tried to install them, from aptitude, the boost libraries site (1.65.1), everything. Even, someone helped me for hours (thanks for your support cawfee ❤️), trying to link the libraries but I couldn't. So, is there any way to do this? I'm currently using Ubuntu 16.04.3.

This is what I get from CMake:
```
-- Configuring done
CMake Error at libs/cmake/AddSAMPPlugin.cmake:2 (add_library):
  Target "discord-connector" links to target "Boost::system" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_samp_plugin)

```

And this is after using make:

```
/usr/bin/ld: cannot find -lBoost::system
collect2: error: ld returned 1 exit status
src/CMakeFiles/discord-connector.dir/build.make:516: recipe for target 'src/discord-connector.so' failed
make[2]: *** [src/discord-connector.so] Error 1
CMakeFiles/Makefile2:294: recipe for target 'src/CMakeFiles/discord-connector.dir/all' failed
make[1]: *** [src/CMakeFiles/discord-connector.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```

Thanks in advance.

**Comment by maddinat0r** [comment]
Boost 1.65.1 is "too new" for CMake. You either have to modify the `FindBoost.cmake` file (shipped with CMake itself) or use an older Boost version like 1.64 or 1.63.

**Comment by juanpenia** [comment]
I just came to say that I could compile it, using FindBoost.cmake, that I found on the issue #2 , but on the server now it displays this error:

`[05:40:25]  Loading plugin: discord-connector.so
[05:40:25]   Failed (plugins/discord-connector.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference)`

**Comment by maddinat0r** [comment]
Your C++ runtime seems to be too old. Did you run the plugin on a different machine than the one you compiled it on?

**Comment by juanpenia** [comment]
Actually, yes. When I uploaded the plugin I compiled it on Ubuntu 16.04 and used it on a machine using 14.04. Now I compiled it on 14.04 but I'll test it in a machine running 16.04 before trying on the main server (which uses 14.04)

**Comment by juanpenia** [comment]
Problem solved after executing the code from here:

https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

**Comment by juanpenia** [comment]
If you want, this is it compiled on Ubuntu 14.04

http://149.202.63.132/123/discord-connector.so

**Comment by maddinat0r** [comment]
Alright, good that it worked out for you 👍
