### ISSUE TITLE
libssl.so.1.1

### ISSUE THREAD

**Issue by viruxe** [maddinat0r/samp-discord-connector#33]
`libssl.so.1.1: cannot open shared object file: No such file or directory`

```
viruxe@Betelgeuse:~/ss$ sudo apt-get install libssl1.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl1.1 is already the newest version (1.1.0f-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
viruxe@Betelgeuse:~/ss$
```

Running Debian 9.1 64bit.

**Comment by maddinat0r** [comment]
You need to install the 32bit libssl package.

**Comment by Southclaws** [comment]
I think things like this should be collated into a Wiki page - I see quite a lot of people who aren't too familiar with Linux packages running into this issue, especially with the different architectures.

If I recall correctly, doesn't this also require running `dpkg --add-architecture i386` before even being able to install 32 bit shared objects or is that just for development libraries?

**Comment by viruxe** [comment]
`apt-get install libssl-dev:i386` did the trick. Thank you.
