### ISSUE TITLE
Discord API - Suggestions

### ISSUE THREAD

**Issue by Zorono** [maddinat0r/samp-discord-connector#39]
Hello everybody,  it 'd be great if you @maddinat0r added an function which sets the game status of the BOT 
For example 
```DCC_SetBotGameStatus('San Andreas Multiplayer'); ```

And an callback which gets called when any new User Joins our DS server for example
```public DCC_OnUserJoinGuild(userID) {…}```
And an callback which gets called when any GuildUser leave our DS server for example 
```public DCC_OnGuildUserLeave(userID)  {…}```

And an function to count how much users exists on our DS server and another function to count how much users exists on an specific role (will be used for debugging)  

For example ```DCC_CountGuildUsers();
DCC_CountGuildUsersByRole(roleID); ```

And an function to count how much channels on our DS server and another function to count how much Categories on our DS server (will be used for debugging) 
For example ```DCC_CountGuildChannels();
DCC_CountGuildCategories();```

And add an official Command processor as we are currently using an unofficial Command Processor by @Xeon http://forum.sa-mp.com/showthread.php?p=3908995#post3908995 

And add some moderating functions for example ```DCC_KickGuildUser(user);  DCC_BanGuildUser(user,  reason{});```

And add some functions to change GuildUser's Roles

**Comment by maddinat0r** [comment]
- function `DCC_SetBotGameStatus` will probably be implemented in the next version
- callback `DCC_OnGuildMemberAdd` already exists
- callback `DCC_OnGuildMemberRemove` already exists
- function `DCC_GetGuildMemberCount` already exists
- counting users with a specific role can be implemented through PAWN with already existing functions
- function `DCC_GetGuildChannelCount` already exists
- counting guild categories can be implemented through PAWN with already existing functions
- banning, kicking, and many more functions will be in the next update

I will not provide a command processor, as I don't see it to be my responsibility. I merely give you the tools to create stuff.

**Comment by JohnMagdy** [comment]
Thanks sir for your response, it 'd be great if you showed me an example about how to check if there is anyone trying to send a PM to the BOT 

i have tried checking the length of the channel name if its less than 1 so its an BOT PM but it didn't work as well

**Comment by maddinat0r** [comment]
You need to check for the channel type:
```pawn
new DCC_ChannelType:type;
DCC_GetChannelType(channel, type);
if (type == DM)
{
	// this is a direct message channel
}
```

**Comment by AliLogic** [comment]
We really need the functionality for updating the Game status (DCC_SetBotGameStatus).

**Comment by maddinat0r** [comment]
Added all bot functions (including setting the bot's game status and creating DM channels) in d338c0658001074e2b1b0c1ff46d8d5ab9c25a84.
