### ISSUE TITLE
Function for bots to PM users

### ISSUE THREAD

**Issue by karimcambridge** [maddinat0r/samp-discord-connector#40]
^ topic.

just like 
```native DCC_SendChannelMessage(DCC_Channel:channel, const message[]);```

we would like
```native DCC_SendUserMessage(DCC_User:user, const message[]);```

**Comment by maddinat0r** [comment]
This functionality will be in the next update.

**Comment by karimcambridge** [comment]
No @nickdodd25 AFAIK.

**Comment by maddinat0r** [comment]
I'm working on adding both of these features into the next update, but I don't know when it'll be ready for release.

**Comment by maddinat0r** [comment]
Implemented in d338c0658001074e2b1b0c1ff46d8d5ab9c25a84.
