### ISSUE TITLE
Can't edit server.cfg on host

### ISSUE THREAD

**Issue by karim-m** [maddinat0r/samp-discord-connector#46]
Alright so the bot token is supposed to be put on server.cfg, but our server host does reset server.cfg everytime server starts (incase someone changes slots or whatever), is there any way to put the token some where else except server.cfg? in a text file maybe or something.

**Comment by maddinat0r** [comment]
I'm not really fond of using a single text file with only the bot token in it. Having that setting in the server config file makes sense and is way more elegant than having it in some random text file.
This is more of a special problem with your host, so I don't really see a need to build in workarounds like these. How do you even configure stuff like your RCON password or streaming settings? Ask your host to allow having persistent settings.

**Comment by karim-m** [comment]
I understand that the server.cfg is the better way for it and I never meant it's a better way but for my case I am stuck with my host because of hosted tab, so I can't switch. I even tried recompiling the plugin after modifying server.cfg to discord.cfg in SampConfigReader.cpp but I have no luck with boost 1.66 that doesn't work with cmake. I'd be more than happy to get the plugin rebuilt in debian with the custom discord.cfg.. Thank you

**Comment by maddinat0r** [comment]
You currently can't build the master branch. Try checking out the v0.2.1 tag. You also should use Boost 1.64 to build it, the README is outdated.
