### ISSUE TITLE
libssl.so.1.1

### ISSUE THREAD

**Issue by dyzio123** [maddinat0r/samp-discord-connector#47]
[22:39:46]  Loading plugin: discord-connector.so
[22:39:46]   Failed (libssl.so.1.1: cannot open shared object file: No such file or directory)

i have debian 9

**Comment by maddinat0r** [comment]
`apt-get install libssl1.1.i386`
Don't forget to enable i386 packages in `dpgk`.

**Comment by dyzio123** [comment]
```
E: Unable to locate package libssl1.1.i386
E: Couldn't find any package by glob 'libssl1.1.i386'
E: Couldn't find any package by regex 'libssl1.1.i386'
```

i enable i386 in dpgk
`dpkg --add-architecture i386`

**Comment by maddinat0r** [comment]
Sorry, my fault. It should be a colon instead of a point:
```bash
apt-get install libssl1.1:i386
```
