### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by HypeSzkodnik** [maddinat0r/samp-discord-connector#49]
Hi, I seriously know nothing about ubuntu/linux. I have hosting game server. I want to install this AMAZING plugin, but! I have got that error:
Loading plugin: discord-connector.so
Failed (/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/discord-connector.so))
Please help!

**Comment by maddinat0r** [comment]
Which download did you use?
