### ISSUE TITLE
Issue with new version

### ISSUE THREAD

**Issue by Chaprnks** [maddinat0r/samp-discord-connector#52]
Since discord uses server.cfg instead of the OnGameModeInit function, how do I change the log level? is there another server.cfg variable I can set?

Thanks!

**Comment by Chaprnks** [comment]
UPDATE:
---------

I decided to simply edit main.cpp; but I'm having some issues with the compile. I've tried using both the master revision & the release revision. After getting the correct boost library compiled from source (too new for my poor old ubuntu), it gives me an error with the amx.h

```
amx.h:153:11: error: unknown type name ‘uint32_t’
   typedef uint32_t  ucell;
```

![aw0xoyo](https://user-images.githubusercontent.com/6340970/37058083-54993a84-2157-11e8-81a4-d05ec9fef8b9.png)

**Comment by maddinat0r** [comment]
The log level is currently hard-coded. This will change in v0.3.
You should definitely use the release branch, the master branch is currently not easily buildable.
How did you run CMake exactly? What CMake variables did you set/adjust?
