### ISSUE TITLE
Invalid UTF8 string + Suggestions

### ISSUE THREAD

**Issue by r4sheed** [maddinat0r/samp-discord-connector#53]
Hey

I've got this error in the log file when i try to send a message (with UTF8 chars (á,é,ű,ó,í,ü etc)) to discord from ingame.
`[ERROR] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 17: 0xF5`

And this is the output when i send message to the server from discord.
https://puu.sh/zFjiB/91021a2f92.png

Suggestion 1: Escape the null strings (when you upload a picture without a message for example) 
Suggestion 2: Do something with the emojis. They looks like this ingame. https://puu.sh/zFjnl/de99c34f65.png

Thanks in advice

**Comment by F96fedebike** [comment]
@r4sheed Hey, you can fix this issue with using this include: https://github.com/oscar-broman/strlib/blob/master/strlib.inc

After you have formatted your string, use this: 
**`utf8encode(dest[], const source[], maxlength = sizeof(dest)`**.

I've try for me and it's working very well!

**Comment by maddinat0r** [comment]
As suggested, you'll need to manually encode and decode text messages to/from Discord.
