### ISSUE TITLE
Posibility of setting user role?

### ISSUE THREAD

**Issue by Cubko** [maddinat0r/samp-discord-connector#54]
Hey, the plugin is nice, keep it up! I wonder if here's implemented native function to set role of an user. I'm looking to create bot with posiblity to set verified role. Is that somehow possible or not yet?

**Comment by Sasuke-Uchiha** [comment]
I use a command in game to set their own discord name, /discord [My Discord Nick] so when I type a command that needs rank, it will compare my discord nick to the account I used that command and get the rank.

**Comment by maddinat0r** [comment]
That functionality is something I'm planning for v0.3. I can't really say though how long it will take until it's ready for release.

**Comment by MrTeamMate** [comment]
Only if it was still 2018 there would be hope for this :(

**Comment by maddinat0r** [comment]
I've added this in 41926fc49215984edd1c7f3eba732a4db32e4dcc, but I still can't give an exact date when the next version will be out. But you can be sure that this feature (`DCC_AddGuildMemberRole` and `DCC_RemoveGuildMemberRole`) will definitely be in the next release.

**Comment by maddinat0r** [comment]
Implemented in said commit. Development builds are available from AppVeyor (click the CI badge on the README) for testing.
