### ISSUE TITLE
Profiler result shocking. 

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [maddinat0r/samp-discord-connector#55]
[discord-profile.zip](https://github.com/maddinat0r/samp-discord-connector/files/1819078/discord-profile.zip)

The result is pretty bad but happened only once in 1055 calls, but for 51 seconds to execute that's what can I say really slow.

**Comment by maddinat0r** [comment]
What plugin version are you using? On what OS did the plugin run?

**Comment by Sasuke-Uchiha** [comment]
Latest, the one you asked me to update. https://github.com/maddinat0r/samp-discord-connector/releases/tag/v0.2.3

And OS is CentOS7

**Comment by maddinat0r** [comment]
I just verified that the commit I made fixed this issue.
Profiler result before that fix:
![capture](https://user-images.githubusercontent.com/1799378/38388164-aff28a90-391a-11e8-9fb7-df4e9a3a67c6.PNG)

Profiler result with that fix:
![capture1](https://user-images.githubusercontent.com/1799378/38388173-bf571320-391a-11e8-9e2b-88a9b7ba6477.PNG)

Look out for 0.2.4, that release will include this fix. I'll close this for now, but feel free to re-open this issue if you still experience your problem after using 0.2.4.
