### ISSUE TITLE
get role id by user name/id

### ISSUE THREAD

**Issue by Trnsmv9** [maddinat0r/samp-discord-connector#57]
Is it possible to get role name/id by user name/id?

DCC_GetRoleId(DCC_Role:role, dest[], max_size = sizeof dest);

"DCC_User"  instead of "DCC_Role"

**Comment by maddinat0r** [comment]
```c
Discord_PrintRolesForServerMember(DCC_Guild:guild, DCC_User:user)
{
	printf("user id %d has these roles:", _:user);
	
	new role_count;
	DCC_GetGuildMemberRoleCount(guild, user, role_count);
	for (new i; i != role_count; i++)
	{
		new DCC_Role:role;
		DCC_GetGuildMemberRole(guild, user, i, role);
		
		new role_name[64];
		DCC_GetRoleName(role, role_name);
		
		new role_id[32];
		DCC_GetRoleId(role, role_id);
		
		printf("\t%s: %s", role_name, role_id);
	}
}
```
This should print something like this to the server console:
```
user id 1 has these roles:
    verified: 425251404144443394
    member: 425251404166663394
    moderator: 425251404177773394
```

**Comment by Trnsmv9** [comment]
Thanks, worked

got new problem with centos 6.9 server

 Failed (libssl.so.1.0.0: cannot open shared object file: No such file or directory)

openssl Version: 1.0.1e (openssl-1.0.1e-57.el6.i686)

installed openssl-devel, openssl-static, openssl-perl  but nothing.

i can't even update openssl (already installed and latest version),  yum install openssl-libs return "No package openssl-libs available." even with openssl-libs:i686/i386

uname -a
Linux Server 2.6.32-696.23.1.el6.i686 #1 SMP Tue Mar 13 23:09:35 UTC 2018 i686 i686 i386 GNU/Linux

tried linux and centos7 plugin both.

**Comment by maddinat0r** [comment]
CentOS 6 (and also CentOS 7 in the next major update) is not supported. The plugin won't run correctly on it.

**Comment by Trnsmv9** [comment]
No way to get centos6.9 plugin compatibility?

Maybe old plugin version

**Comment by maddinat0r** [comment]
You can try compiling it by yourself, but I won't provide any support regarding this.

**Comment by Trnsmv9** [comment]
after "make" into build folder  i got the following error:

/samp-discord-connector/libs/json/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"

The link show the supported version of gcc, GCC 4.9 - 7.2 (and possibly later)

i have gcc 4.9.1, cc 4.9.1 and g++ 4.9.1 version and it still gave same error

what's version json support?

**Comment by maddinat0r** [comment]
As I wrote before, I won't provide any support for this.
I'll close this, as the original question has been answered.
