### ISSUE TITLE
Unnecessary pawn.json backslashes

### ISSUE THREAD

**Issue by MichaelBelgium** [maddinat0r/samp-discord-connector#59]
(Moved my comment from pull request #58 to an issue)

There's a small mistake:

`"plugins": ["discord-connector-.+\\/plugins\\/discord-connector\\.so"],`

should be
`"plugins": ["discord-connector-.+\\/plugins\\/discord-connector.so"],`

Same with the .dll most likely. When i execute sampctl server ensure
it downloads `discord-connector\.so` to my plugins folder, so thats the cause.

Also as the releases have multiple versions for linux dists, it might be not working on debian 9 for example (yet). But there's nothing to do about that - Southclaws said 
> I need to resolve that similar to the problem with IRC which has SSL and non-SSL versions - I plan to fix this with resource "labels" to select different files

I was planning to do a PR when Southclaws was ready with that version

**Comment by maddinat0r** [comment]
Hm, this is getting kinda hard to understand. As I understood it, those strings are regular expressions. Since `.` is a regex specifier, you'd have to escape it. I assumed that `\` is the escape character, so it would make sense there. However I'm now starting to wonder why we'd need to escape forward slashes.
@Southclaws is there a standard way to do this? Is this documented somewhere?

**Comment by MichaelBelgium** [comment]
Mhm it's a file name with extension so applying regular expressions is not needed afaik. Take a look at the [json](https://github.com/pBlueG/SA-MP-MySQL/blob/master/pawn.json#L10) of mysql, it's the same thing

**Comment by Southclaws** [comment]
Oh that is weird, I would assume the `\\.` is correct but maybe I accidentally used the tail of the regex as the filename... I shall have a look at this in the morning.

**Comment by seanny** [comment]
I have made some changes to fix this in PR #60

**Comment by Southclaws** [comment]
The point here is there shouldn't be an issue with the pawn.json, it's more likely a problem with sampctl - you shouldn't need to change the definition.

**Comment by MichaelBelgium** [comment]
Ok, [sampctl 1.7.11](https://github.com/Southclaws/sampctl/releases/tag/1.7.11) fixes this. So no need to change the `pawn.json` (#60). Thx @Southclaws - I believe I can close this.
