### ISSUE TITLE
Compling C++

### ISSUE THREAD

**Issue by LVPYassine** [maddinat0r/samp-discord-connector#6]
Hello maddinator !

when i try to complie the plugin 
it's always says;

> CMake Error at CMakeLists.txt:29 (message):
  Could NOT find Boost; specify additional paths.

**Comment by Southclaws** [comment]
Check #2 it might help.

**Comment by LVPYassine** [comment]
Thank you but while build the Solution it's says 45 Errors and Warnings :/

**Comment by maddinat0r** [comment]
Did you correctly followed the [build instruction](https://github.com/maddinat0r/samp-discord-connector#build-instruction)?

**Comment by LVPYassine** [comment]
Yes.

**Comment by maddinat0r** [comment]
Doesn't matter, one depends on the other. I'd build the `PACKAGE` target though. This will give you a nice zip file with everything you need.

**Comment by LVPYassine** [comment]
logs:

`1>------ Build started: Project: PACKAGE, Configuration: Release Win32 ------
1>  CPack: Create package using ZIP
1>  CPack: Install projects
1>  CPack: - Install project: discord-connector
1>  CMake Error at C:/Users/Yassine/Desktop/samp-discord-connector-master/build/src/cmake_install.cmake:34 (file):
1>    file INSTALL cannot find
1>    "C:/Users/Yassine/Desktop/samp-discord-connector-master/build/src/Release/discord-connector.dll".
1>  Call Stack (most recent call first):
1>    C:/Users/Yassine/Desktop/samp-discord-connector-master/build/cmake_install.cmake:33 (include)
1>
1>
1>EXEC : CPack error : Error when generating package: discord-connector
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: cd C:\Users\Yassine\Desktop\samp-discord-connector-master\build
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: C:
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by maddinat0r** [comment]
What errors do you get during compile?

**Comment by LVPYassine** [comment]
http://i.imgur.com/vmEtuM0.png

first one x 14

**Comment by maddinat0r** [comment]
That's the CPack error, which implies that there is no `discord-connector.dll` plugin file. And this will likely mean that there are compile errors during the actual plugin build. I'm interested in those errors.
Do a full clean of your solution and compile the `ALL_BUILD` target.

**Comment by LVPYassine** [comment]
i got 50 errors & 2 warnings in Release mode same thing in Debug mode

http://imgur.com/a/gA3km

**Comment by maddinat0r** [comment]
Which Visual compiler version are you using?

**Comment by LVPYassine** [comment]
Visual Studion 14.*** 2015

also can you come to discord to talk easy ? https://discord.gg/SxmdAJN

**Comment by maddinat0r** [comment]
Could you share your full build log please?

**Comment by LVPYassine** [comment]
1- i downloaded boost 1.62.0 
2- i used bootstrap.bat in boost libary
3- also ex the bjam.exe app 
4- changed the directorys in CMake DIR
5- Download Open SSL
6- Edited Directorys

it's show like that:
![capture](https://cloud.githubusercontent.com/assets/19735645/22405403/fba253f6-e639-11e6-9543-e558f543b675.PNG)

7- after build i pressed Open Project
8- i builded the ALL_BUILD Project as a Release
9- it's gave me the errors ^^^

**Comment by maddinat0r** [comment]
Sorry, by build log I meant the textual output window in Visual Studio which opens when you start compiling.

**Comment by LVPYassine** [comment]
Thank you for you time :)

it's give me this logs:

for debug: http://pastebin.com/wWhbgvYC
for release: http://pastebin.com/ivZw6uyb

also if you want do you can join discord ? there we can talk easy

**Comment by maddinat0r** [comment]
I want to keep everything here in this issue.
You seem to be using an old version of VS2015, where the compiler has some bugs which violate the C++11 standard. Update it to the latest version (14.3 I think; Visual Studio 2015 Update 3).

**Comment by LVPYassine** [comment]
i lost Visual Studio Pro 2015
 i will download the VS C 2017 one

**Comment by LVPYassine** [comment]
can you give me the right OpenSSL Libary again ? i lost it
