### ISSUE TITLE
Russian language?

### ISSUE THREAD

**Issue by ShimaNeko** [maddinat0r/samp-discord-connector#62]
![image](https://user-images.githubusercontent.com/26200890/38906538-f228dbc2-42bf-11e8-971f-e24f083cefd3.png)

> DCC_SendChannelMessage(g_AdminChannelId,"TEST");
> DCC_SendChannelMessage(g_AdminChannelId,"А ШО ПО РУССКОМУ ЯЗЫКУ ЗНАЧЭЦЦА)))))))");

![image](https://user-images.githubusercontent.com/26200890/38906559-0cb2f252-42c0-11e8-9c38-e3ee6d968bf4.png)
Cyrillic please
`[04/18/18 03:19:56] [ERROR] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xDB
`

**Comment by maddinat0r** [comment]
See issue #27 and [this post](http://forum.sa-mp.com/showpost.php?p=3979019&postcount=131).
