### ISSUE TITLE
Russian language & Role in DCC_OnChannelMessage

### ISSUE THREAD

**Issue by FelixKot** [maddinat0r/samp-discord-connector#63]
Plugin does not support Russian language.  Is it possible to fix? This is a big problem for me and my server.

**Comment by FelixKot** [comment]
found a solution to the problem with the output of the message from the mod to the discord. But I don't know how to fix the output from discord to the server

**Comment by FelixKot** [comment]
Another question. If not too much trouble give a code example how to learn the Role in DCC_OnChannelMessage

**Comment by maddinat0r** [comment]
Text messages from Discord are encoded in UTF8, so you'll have to decode them into your desired character set.

Here's your example code:
```pawn
public DCC_OnChannelMessage(DCC_Channel:channel, DCC_User:author, const message[])
{
	new DCC_Guild:guild;
	if (!DCC_GetChannelGuild(channel, guild))
		return 0; // error
	
	new role_count;
	if (!DCC_GetGuildMemberRoleCount(guild, author, role_count))
		return 0; // error
	
	for (new r; r != role_count; r++)
	{
		new DCC_Role:role;
		DCC_GetGuildMemberRole(guild, author, r, role);
	}
	return 1;
}
```

**Comment by FelixKot** [comment]
Thank you.

**Comment by maddinat0r** [comment]
What colors? Be more specific please.

**Comment by maddinat0r** [comment]
`DC_GetRoleColor` fetches the role color. You can't make colored text messages in Discord.

**Comment by ByvDeveloper** [comment]
@FelixKot Sorry, but how you solved this problem?
I'm tried format text to utf 8 via [strlib](https://github.com/oscar-broman/strlib) before send to discord, but if i send it from chat (or use format() before send) - it's not converted.
Any ways to resolve?
