### ISSUE TITLE
Can you explain me that?

### ISSUE THREAD

**Issue by Walter-Correa** [maddinat0r/samp-discord-connector#64]
Sorry for ignorance, but could you ask me how to use the following parameters?
DCC_GetGuildMemberRole(DCC_Guild:guild, DCC_User:user, offset, &DCC_Role:role);

offset - What is this and how do I use it?
&DCC_Role:role - The role ID, right?

Thank you!

**Comment by maddinat0r** [comment]
A user can have multiple roles assigned, that's why you have to pass an offset on what role to retrieve. Use `DCC_GetGuildMemberRoleCount` to get the number of roles he has. That way you can also iterate through all roles:
```pawn
new count;
DCC_GetGuildMemberRoleCount(guild, user, count);
for (new i; i != count; i++)
{
    new DCC_Role:role;
    DCC_GetGuildMemberRole(guild, user, i, role);
    
    new role_name[128];
    DCC_GetRoleName(role, role_name);
}
```

**Comment by Walter-Correa** [comment]
Dude, thanks a lot! Congratulations on this plugin, it's perfect!

**Comment by maddinat0r** [comment]
You’re welcome.
