### ISSUE TITLE
I can not make it work...

### ISSUE THREAD

**Issue by Walter-Correa** [maddinat0r/samp-discord-connector#65]
new DCC_UserPresenceStatus:status;
DCC_GetGuildMemberStatus(server, userid, status);

**Tried:** if(status != ONLINE)//**It says the player is online for all status.**

**Tried:** if(status != DCC_UserPresenceStatus:ONLINE)//**It says the player is not online even though.**

**EDIT:** How to mention a user?

Thank you!

**Comment by maddinat0r** [comment]
The `DCC_GetGuildMemberStatus` is currently not working correctly. This will be resolved in the next update.
For mentioning users, write `<@!UserId>`, where `UserId` is the id you get from the `DCC_GetUserId` function.

Feel free to close this issue if your questions are answered.

**Comment by Walter-Correa** [comment]
Thank you very much for your reply! Worked perfectly!
I hope you can make the `DCC_GetGuildMemberStatus` function work.

**Last question:** How do I mention a Role?
