### ISSUE TITLE
Some suggestions for future versions

### ISSUE THREAD

**Issue by Walter-Correa** [maddinat0r/samp-discord-connector#66]
I do not know if it is possible, but it would be great to have the following functions:
`DCC_SetGuildMemberRole`
`DCC_MoveGuildMemberChannel` or `DCC_SetGuildMemberChannel`
`DCC_SendGuildMemberMessage`
`DCC_GetGuildMemberChannel`

**Comment by maddinat0r** [comment]
There are a lot of functions missing, I'm aware of that. That's why it's still in beta stage. I've planned to add those functions and a lot more in the next major update.
