### ISSUE TITLE
incorrect channel and member count in plugin cache

### ISSUE THREAD

**Issue by Walter-Correa** [maddinat0r/samp-discord-connector#67]
The same: http://forum.sa-mp.com/showpost.php?p=4022363&postcount=162

**Comment by maddinat0r** [comment]
Can you reliably reproduce that issue? If yes, provide the code you used and the full `discord-connector.log` plugin log file.

**Comment by Walter-Correa** [comment]
**Well, using the same code from:** http://forum.sa-mp.com/showpost.php?p=4022363&postcount=162

**Total members in my server:** http://prntscr.com/jmlbiy
**Total Roles:** http://prntscr.com/jmle83
**Channels and Category:** http://prntscr.com/jmlf0m
**Total Official Members(Blue Role):**  http://prntscr.com/jmlgf0
**Result:** http://prntscr.com/jmlk76
**Discord-connector log(Started the server and executed the code only):** http://prntscr.com/jmliel

**Comment by Walter-Correa** [comment]
`DCC_IsUserVerified(user, is_verified);`
**Always says user is not verified**

**Comment by maddinat0r** [comment]
I've fixed the channel categories (and voice channels) not being cached properly in f990f8ef6cf4de1708ce36d5ee564a1b68d20b2d.
The incorrect member count is something I've reproduced, but I still have to investigate that further.

**Comment by maddinat0r** [comment]
Feel free to try a dev build from AppVeyor: https://ci.appveyor.com/project/maddinat0r/samp-discord-connector (select a successful build job with config = Release and image = Windows/Ubuntu (depending on whether you need a Windows or Linux build and click on artifacts)

**Comment by maddinat0r** [comment]
Should be fixed in v0.3.
