### ISSUE TITLE
libssl.so.1.1 - Ubuntu

### ISSUE THREAD

**Issue by WiltonFreitas** [maddinat0r/samp-discord-connector#69]
Hello,

Recently I started use your plugin in my gamemode but he show me this error in my Ubuntu when I start my sa-mp server.

```
[21:01:02]  Loading plugin: discord-connector.so
[21:01:02]   Failed (libssl.so.1.1: cannot open shared object file: No such file or directory)
```

I saw others issues report with same problem and following the instructions I uses the **apt-get install openssl-libs.i686** but nothing changes, instead this linux command show me this error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssl-libs.i686
E: Couldn't find any package by regex 'openssl-libs.i686'
```

What I do to use correctly your plugin?

**Comment by maddinat0r** [comment]
Execute `dpkg --add-architecture i386`, run `apt update` and try installing the package again.

**Comment by WiltonFreitas** [comment]
I fix using libbsl 1.0.0 and using the plugin linux package. Thanks bro.

Another question, it's normally the plugin don't send all messages using DCC_SendChannelMessage?

The 5, 11 and 17 wasn't sended.
`
Jarvis BOT - Today in 6:04 PM
stress test - 0
stress test - 1
stress test - 2
stress test - 3
stress test - 4
stress test - 6
stress test - 7
stress test - 8
stress test - 9
stress test - 10
stress test - 12
stress test - 13
stress test - 14
stress test - 15
stress test - 16
stress test - 18
stress test - 19`

**Comment by VictorFerraresi** [comment]
I'd say that has to do with Discord's API default throttling/rate limit since the posting speed of your code is probably defined by a linear for execution (for x from a to b do sendMessage).

Try sleeping() somewhere inside this loop for something like 200ms and retry.

**Comment by maddinat0r** [comment]
This is also because the plugin uses the system time to check when the rate limit is lifted, so make sure your system clock is synced regularly. This behavior will be fixed in the new release, as I'm now parsing the date header from the HTTP response and use that date instead of the system clock.
