### ISSUE TITLE
unexpected DCC_GetGuildOwnerId value

### ISSUE THREAD

**Issue by JohnMagdy** [maddinat0r/samp-discord-connector#70]
Hello dude, so iam trying to check where the User is the Server Owner by his/her DCC_User but unfortunately always return `True` for anyone.

Code: 

```
DS_IsGuildUserOwner(DCC_Guild:guild, DCC_User:user)
{
    new ds_ownerid[100], ds_userid[100];  
	DCC_GetGuildOwnerId(guild, ds_ownerid); DCC_GetUserId(user, ds_userid);
	
	return (strcmp(ds_ownerid, ds_userid, false) == 0 ? (true) : (false));
}
```

Expected Return-Value: `False`
Result: `True`

**Comment by maddinat0r** [comment]
Do the natives return `true` or `false`? Do the variables contain a valid snowflake id? Are there any errors logged in the plugin log file?

**Comment by JohnMagdy** [comment]
Do the natives return: `True` (DCC_GetGuildOwnerId,DCC_GetGuildOwnerId but at other cases tbh i don't know if it works as well with this function)
 Do the variables contain a valid snowflake id:  no 80% (iamn't sure if iam checking for the validation of the ID correctly...
```
DS_IsGuildUserOwner(DCC_Guild:guild, DCC_User:user)
{
    new ds_ownerid[100], ds_userid[100];  
	DCC_GetGuildOwnerId(guild, ds_ownerid); DCC_GetUserId(user, ds_userid);
	
	return (strlen(ds_ownerid) > 7 && strlen(ds_userid) > 7 ? strcmp(ds_ownerid, ds_userid, false) == 0 : false);
}
```
Are there any errors logged in the plugin log file:
```
 can't update guild member presence: guild id "online" not cached
```

**Comment by Dayrion** [comment]
```pawn

DS_IsGuildUserOwner(DCC_Guild:guild, DCC_User:user)
{
	new ds_ownerid[19], ds_userid[19]; 
	DCC_GetGuildOwnerId(guild, ds_ownerid);
	DCC_GetUserId(user, ds_userid);
	return (!strcmp(ds_ownerid, ds_userid, false));
}
```
Everything is working for me. Make sure you have correctly configured your bot, the guild id is the right one and same thing for the user.

**Comment by JohnMagdy** [comment]
@Dayrion for me it's not working as expected...
when trying to test it with multiple users (Bots, me, My friends)... but it detects everyone as Guild Owner...

Code:
```
DS_IsGuildUserOwner(DCC_Guild:guild, DCC_User:user)
{
	new ds_ownerid[19], ds_userid[19];

	if(!DCC_GetGuildOwnerId(guild, ds_ownerid))
		return 0;
	if(!DCC_GetUserId(user, ds_userid))
		return 0;

	return (!strcmp(ds_ownerid, ds_userid, false));
}

	  if(DS_IsGuildUserOwner(ds_guild, user))
	  {
	     format(ds_string, sizeof(ds_string), "- Username: <@%s> :crown:", ds_usrID); DCC_SendChannelMessage(DCC_FindChannelByName(channel), ds_string);
	  }
	  else
	  {
	     format(ds_string, sizeof(ds_string), "- Username: <@%s>", ds_usrID); DCC_SendChannelMessage(DCC_FindChannelByName(channel), ds_string);
	  }
```

![capture](https://user-images.githubusercontent.com/19735243/42479379-ef4d7f7a-83d8-11e8-9bd2-a177d377f996.JPG)

**Comment by maddinat0r** [comment]
I'm not able to verify this issue. `DCC_GetGuildOwnerId` seems to be working fine.
