### ISSUE TITLE
Embed messages.

### ISSUE THREAD

**Issue by ynhhoJ** [maddinat0r/samp-discord-connector#72]
How I can send embed messages?

This method did not work:
```pawn
new str[56+1];
format(str, sizeof str, "{embed:{color:3447003,description:'verysimpleEmbed!''}}");
DCC_SendChannelMessage(g_WelcomeChannelId, str);
```

**Comment by maddinat0r** [comment]
You currently can't send embeds, this has to be supported by the plugin. This will probably be implemented some time after v0.3.

**Comment by Dayrion** [comment]
At least, you can "embed" your message by using markdown style.
`Like this` or 
```c
a:like this() "one"
```
You can do some cool & colored stuffs.

**Comment by lJohhnyl** [comment]
@Dayrion , can you show pls a full example?
