### ISSUE TITLE
Set path for logs ?

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#74]
Is there a way to to change Logs path? 

PS: How to use "E_LOGLEVEL" in functions/callbacks ? where to change it?

**Comment by maddinat0r** [comment]
You currently can't change the log level because it's hard-coded into the plugin. This will change in 0.3 I presume.
Changing the log folder is not possible yet. I suggest creating a feature request for this in the [log-core](https://github.com/maddinat0r/samp-log-core) repository.

**Comment by Yousha** [comment]
Hmm, can you at-least change it(hard coding) to `scriptfiles` directory? 
Using root directory for data related files is bad idea...

**Comment by maddinat0r** [comment]
As I said, open up a new issue for this in the log-core repository. This has nothing to do with the discord-connector itself, as the logging system is a centralized, external library.
