### ISSUE TITLE
Error while sending WS close frame: stream truncated

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#75]
Everything is fine, but I'm getting this error for no reason: (I don't have SSL)

> [plugins/discord-connector] Error while sending WS close frame: stream truncated (1)
> [plugins/discord-connector] Error while shutting down SSL on HTTP connection: stream truncated (1)

Plugin: 0.2.3
SAMP: 0.3.7-R2
OS: Windows 7 32bit
Hardware: Intel x64

**Comment by maddinat0r** [comment]
Mostly fixed.
