### ISSUE TITLE
Too many random errors/warnings

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#76]
We don't use SSL:

1
> [07/15/18 14:17:23] [plugins/discord-connector] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 20: 0xD1
> [07/15/18 17:18:40] [plugins/discord-connector] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 12: 0xE4
> [07/15/18 17:19:09] [plugins/discord-connector] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 18: 0xD3

2
> [07/15/18 13:44:18] [plugins/discord-connector] can't update guild member presence: guild id "offline" not cached

3
> [07/15/18 13:48:10] [plugins/discord-connector] can't update guild member presence: guild id "dnd" not cached

4
> [07/15/18 14:00:43] [plugins/discord-connector] Error while shutting down SSL on HTTP connection: short read (335544539)

5
> [07/15/18 14:00:43] [plugins/discord-connector] Error while retrieving HTTP POST response from '/api/v6/channels/455663109861015562/messages': short read

6
> [07/15/18 13:44:15] [plugins/discord-connector] can't update guild member presence: guild id "online" not cached

**Plugin: 0.2.3
SAMP: 0.3.7-R2
OS: GNU/Linux 32bit**

**Comment by maddinat0r** [comment]
1: You're passing an invalid UTF-8 string to `DCC_SendChannelMessage`. Discord uses UTF-8 exclusively, and thus expects UTF-8 encoded messages. You'll also get UTF-8 encoded messages back from Discord.
2, 3, 6: See #71.
4, 5: Those errors on connection close are mostly fixed by now. Expect them in the next release.

**Comment by Yousha** [comment]
Thanks!
About **#1**, I think it's because some players are using special chars in their messages(non-ascii and non-utf)... is there a way to fix it?

**Comment by maddinat0r** [comment]
AFAIK Slice made an include with some string functions, some of them being UTF encode/decode functions.
