### ISSUE TITLE
Suggestion/Question: Re-connect the bot ?

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#77]
Is there any API/function to **re-connect** the bot?
What if bot getting disconnected while server is up? by a bug/mistake

_PS: or even better, make the connection manually, instead of on plugin startup._

**Comment by maddinat0r** [comment]
The bot always attempts to stay online. That means reconnection is handled completely by the plugin.
If you experience any case where the bot seems to be offline/unresponsive, and you're sure that the Discord servers and API are fully working, open a new issue, as that's a bug.

**Comment by Yousha** [comment]
Now we got this error due to Discord's server problem and Bot got disconnected... 
So bot couldnt re-connect again:

> [plugins/discord-connector] Can't read from Discord websocket gateway: Connection reset by peer (104)
> [plugins/discord-connector] Can't establish secured connection to Discord gateway: Connection reset by peer (104)
> [plugins/discord-connector] Error while retrieving HTTP POST response from '/api/v6/channels/466704292724736002/messages': short read
> [plugins/discord-connector] Error while retrieving HTTP POST response from '/api/v6/channels/466704292724736002/messages': short read

> [plugins/discord-connector] Error while shutting down SSL on HTTP connection: short read (335544539)
> [plugins/discord-connector] Error while shutting down SSL on HTTP connection: short read (335544539)
