### ISSUE TITLE
Just a Suggestion

### ISSUE THREAD

**Issue by rajabilal555** [maddinat0r/samp-discord-connector#8]
Well here's a suggestion you can also use,
[**samp.js**](http://forum.sa-mp.com/showthread.php?t=580064)
With
[**Discord.js - Module for node.js**](https://discord.js.org/#/)

but I don't know how it can be implemented into **samp.js** I mean I just found out about **samp.js**...
I want my app.js _(which is actually a discord bot file (can be run by returning `node app.js` in the console))_
and I wan't to get those messages... or actually send messages in a channel to user... and when there is a new messages in a specific channel I want to send it to the player...
example usage of **discord.js**
```javascript
/*
  A ping pong bot, whenever you send "ping", it replies "pong".
*/

// import the discord.js module
const Discord = require('discord.js');

// create an instance of a Discord Client, and call it bot
const bot = new Discord.Client();

// the token of your bot - https://discordapp.com/developers/applications/me
const token = 'your bot token here';

// the ready event is vital, it means that your bot will only start reacting to information
// from Discord _after_ ready is emitted.
bot.on('ready', () => {
  console.log('I am ready!');
});

// create an event listener for messages
bot.on('message', message => {
  // if the message is "ping",
  if (message.content === 'ping') {
    // send "pong" to the same channel.
    message.channel.sendMessage('pong');
  }
});

// log our bot in
bot.login(token);
```

**Comment by maddinat0r** [comment]
There's absolutely no point in this suggestion.
It's like you suggesting me, after I built a house out of wood, to rather use concrete for everything. What should I do with that suggestion? The house is already built and looking pretty good (apart from a minor details and some bugs crawling here and there).
