### ISSUE TITLE
Timeout while initializing data - in Local Host

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#80]
discord-connector plugin is not able to initialize data and **stucks**

Server type
=====
Local host, ports are open and Firewall is off

Plugin logs
=====
All empty, only **discord-connector.log**
`[15:57:47] [INFO] changed log level from 'warning, error' to 'info, warning, error'`

SAMP logs
=====

**Starting server:**

```
Loading plugin: discord-connector.dll
 >> plugin.dc-connector: timeout while initializing data.
                         plugin will proceed to retry connecting in the background.
  Loaded.
```

**Shutting down server:** 

```
--- Server Shutting Down.
plugin.dc-connector: Unloading plugin...
```

Version info
=====
Plugin version: 0.2.4
SAMP version: 0.3.7-R2
OS: Windows 10 64bit
Hardware: x64 Intel

_Note: crashdetect and nativechecker plugins are loaded.
Note 2: Runtime libraries(both 64bit/32bit) are installed._

**Comment by maddinat0r** [comment]
I can't help you without having any log files. Please provide some or close this issue if it isn't relevant to you anymore.

**Comment by maddinat0r** [comment]
Just to be clear: you start the server, the plugin prints out `timeout while initializing data` on startup, and the `discord-connector.log` stays empty (apart from the single "log level changed")?

**Comment by Yousha** [comment]
**server_log.txt**
[10:42:06]  Loading plugin: discord-connector.dll
[10:42:26]  >> plugin.dc-connector: timeout while initializing data.
[10:42:26]                          plugin will proceed to retry connecting in the background.


**discord-connector.log**
[10/27/18 10:42:06] [INFO] changed log level from 'warning, error' to 'info, warning, error'

**Comment by maddinat0r** [comment]
It's weird that the plugin times out without any error message at all. I can't say much more without debug logs, however the log levels are hardwired into the plugin. This will change with the next update, so I'll have to ask you to wait for v0.3 to reproduce it again.

**Comment by maddinat0r** [comment]
Feel free to try a dev build from AppVeyor: https://ci.appveyor.com/project/maddinat0r/samp-discord-connector (select a successful build job with config = Release and image = Windows/Ubuntu (depending on whether you need a Windows or Linux build and click on artifacts)
Then create a file named `log-config.yml` and place it into your server root directory. Paste this into the log config file:
```yaml
Logger:
  plugins/discord-connector:
    LogLevel: All
```
And the plugin should log everything. Don't forget to recompile your gamemode, as the include changed.

**Comment by VinZ3105** [comment]
Yousha , did you success to fix this issue?please give me advice if you already fixed this issue.. im facing same issue..

**Comment by Yousha** [comment]
@VinZ3105 No.

**Comment by Gellboyss** [comment]
I got same problem

**Comment by mhyunata** [comment]
@maddinat0r  do you even realized that your discord connector is just slower at any time, its broken. We all waiting for your new release. your discord connector makes our server delay.

**Comment by DEntis-T** [comment]
we need fixes.
