### ISSUE TITLE
CentOS 7.1 - libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pnshr** [maddinat0r/samp-discord-connector#81]
The plugin loads and works fine on my localhost, Windows 10 OS.
But on my VPS, it refuses to load, any solutions? (centos-7.1-x86_64)

**Comment by maddinat0r** [comment]
You'll have to install the 32bit openssl shared library for the plugin to work.
CentOS also isn't officially supported by this plugin, so if you run into other issues after resolving that one, I'll not be able to help you.

**Comment by pnshr** [comment]
Do you, by any chance, know the command used to install the library via SSH? I've actually been searching before I posted here to no avail. Thanks in advance.

**Comment by maddinat0r** [comment]
```
yum install openssl-libs.i686
```
