### ISSUE TITLE
Allow setting of the bot token via environment variable

### ISSUE THREAD

**Issue by spacemud** [maddinat0r/samp-discord-connector#85]
I'm converting my gamemode to be configured entirely from environment variables. I want to avoid storing sensitive credentials in files.

Could the plugin also look for an environment variable, say `DISCORD_BOT_TOKEN`, and load the token from that?

**Comment by karimcambridge** [comment]
why?

what about multiple gamemodes?

**Comment by spacemud** [comment]
It's a fairly standard practice to store configuration in the environment.
See the Twelve Factor App: https://12factor.net/config

Using env vars for configuration avoids the risk of accidentally checking
in sensitive credentials to version control. It's also a neat way to
centralise all your configuration rather than having one file for database
stuff, another for IRC and so on.

In any case this proposal suggests simply adding a configuration method
rather than replacing the usual practice of setting the bot token. That
might suit you better.

**Comment by karimcambridge** [comment]
I try not to think about myself when these development changes are requested with any plugin/service relating to samp.

Many people develop multiple gamemodes on the same machine & on the same user account.

This is a conflict of interest.

The already `discord_bot_token` already centralises the configuration as its read from `server.cfg`. Which makes it PER server.

I understand what you are asking here, I don't care if its added. I just hope if its added its 'exposed' as a secondary / unpreferred option and not the main option or else people might be confused when their other servers tries to load the wrong bot...

**Comment by maddinat0r** [comment]
Done through #86. Using the environment variable is entirely optional. If it's not defined or empty, the plugin will use the token from the `server.cfg` file like usual.
