### ISSUE TITLE
Suggestions for the new release

### ISSUE THREAD

**Issue by AliLogic** [maddinat0r/samp-discord-connector#87]
The native
`native DCC_SendChannelMessage(DCC_Channel:channel, const message[]);`
should be `native DCC_Message:DCC_SendChannelMessage(DCC_Channel:channel, const message[]);`

So the sent message's ID will be stored in a variable to be used later for the newly added native:
`native DCC_DeleteMessage(DCC_Message:message);`

**Comment by Zorono** [comment]
i agree with your great thinking :D

**Comment by maddinat0r** [comment]
The problem is that the plugin starts tracking messages when Discord reports them as created, i.e. in `DCC_OnMessageCreate`. I can't return a message reference directly from `DCC_SendChannelMessage`, because at that point the message doesn't exist.

**Comment by AliLogic** [comment]
So how would we check what message it was then?

**Comment by maddinat0r** [comment]
That's a good question.
I could add an option to specify a result callback that gets called after the message was sent, with a native to retrieve a `DCC_Message` variable for that message.

**Comment by AliLogic** [comment]
Cool. Looking forward to this - I'm using the latest commit now, will keep you updated with how everything goes :)

**Comment by Zorono** [comment]
can anyone release compiled beta release? ( latest commits' ...)

**Comment by AliLogic** [comment]
Furthermore, can we have the supports for embed? It's not really going to be hard to implement that considering all what you have to do is pass the parameters in a JSON format (if i'm not wrong!)

**Comment by maddinat0r** [comment]
Embeds are not a priority and thus won't be in the upcoming v0.3 release.

**Comment by maddinat0r** [comment]
Added the ability to specify result callbacks in `DCC_SendChannelMessage` (see aa5f2ea232108f9c0a0dab91c8dddee6bf74af34).
Embeds have already an open issue, so I'll close this one.
