### ISSUE TITLE
function not registered

### ISSUE THREAD

**Issue by stephanvebrian** [maddinat0r/samp-discord-connector#88]
Hello sir, i got 
Error : Function not registered : 'DCC_FindChannelById'
     ......................................................... 'DCC_SendChannelMessage'
 .......................................................... 'DCC_GetChannelName'
........................................................... 'DCC_GetUserName'

even im already include discord-connector,

im tryting find thread in the forum but it said i dont have access.. Thanks

**Comment by maddinat0r** [comment]
Either your plugin and include version are mismatched, or the plugin can't start up. Check the log files for error and make sure you use the correct plugin version. Don't forget to recompile your scripts with the correct include.
