### ISSUE TITLE
Unable to Compile (cmake)

### ISSUE THREAD

**Issue by rajabilal555** [maddinat0r/samp-discord-connector#9]
I am sorry for my previous Issue... I understand it was useless...

I am unable to compile this project on my Linux(Debian 7 Wheezy) Machine(VPS [OpenVZ]) 

```bash
root@samp:~# cd /home
root@samp:/home# cd samp-discord-connector/samp-discord-connector
root@samp:/home/samp-discord-connector/samp-discord-connector# cd build
root@samp:/home/samp-discord-connector/samp-discord-connector/build# cd ..
root@samp:/home/samp-discord-connector/samp-discord-connector# ls
CMakeLists.txt  README.md     build                     libs
LICENSE         appveyor.yml  discord-connector.inc.in  src
root@samp:/home/samp-discord-connector/samp-discord-connector# cd build
root@samp:/home/samp-discord-connector/samp-discord-connector/build# ls
CMakeCache.txt  CPackConfig.cmake        libs
CMakeFiles      CPackSourceConfig.cmake  src
root@samp:/home/samp-discord-connector/samp-discord-connector/build# cmake ..
-- CMake version: 3.7.2
-- Build type:
CMake Error at libs/samp-log-core/src/CMakeLists.txt:29 (target_compile_features):
  target_compile_features The compiler feature "cxx_inheriting_constructors"
  is not known to CXX compiler

  "GNU"

  version 4.7.2.


CMake Error at src/CMakeLists.txt:50 (target_compile_features):
  target_compile_features The compiler feature "cxx_inheriting_constructors"
  is not known to CXX compiler

  "GNU"

  version 4.7.2.


-- Configuring incomplete, errors occurred!
See also "/home/samp-discord-connector/samp-discord-connector/build/CMakeFiles/CMakeOutput.log".
See also "/home/samp-discord-connector/samp-discord-connector/build/CMakeFiles/CMakeError.log".
root@samp:/home/samp-discord-connector/samp-discord-connector/build#

```
how can I fix this...
i cloned this repo with this 
```bash
git clone https://github.com/maddinat0r/samp-discord-connector.git
cd samp-discord-connector
git submodule update --init --recursive
```
And I think I have all the submodules
`Cmake --version` returns `cmake version 3.7.2`
And I have `Boost libraries (version 1.62)` installed

Can any one tell me how can I fix this...

**Comment by maddinat0r** [comment]
You need at least GCC 4.8 to compile this plugin.

**Comment by rajabilal555** [comment]
I think that's not available on debian wheezy... And I don't want to crash my machine on whichmy server is running ...
But still I got 2 options...

- Compile GCC 4.8 on my machine and install it (you need to tell me how can I do that)
- Compile this plugin on windows, but will I be able to run it on Linux then?

**Comment by maddinat0r** [comment]
Compiling gcc isn't really an option, as you'd have to install it afterwards anyways (it also takes a lot of resources to compile it). So you could simply download a deb package with gcc 4.8 and install that directly. However, this could mess things up if not done correctly.
You also could compile the plugin in a VM, however you'd still need the C++ runtime installed on your server, and this again could mess up things if not done correctly.
Your best shot is to either upgrade to Jessie or find a safe way to install the C++ runtime GCC 4.8 comes with.
