### ISSUE TITLE
Docker issues & Port query

### ISSUE THREAD

**Issue by LewisBelton** [maddinat0r/samp-discord-connector#91]
Evening,

I've been trying for days to get your plugin working with SAMPctl, everything is working fine apart from the plugin won't connect. It's all running in a docker container via Pterodactyl on Ubuntu Server 18.04. If I navigate to the Servers container, and then run `sampctl p build` the plugin connects fine although if I run the same command from the panel it fails, does your plugin use a specific port by any chance.

Sorry the logs literally say -8 timeout, nothing else.

**Comment by maddinat0r** [comment]
Try checking the plugin log, it should be in your server root directory under logs/plugins/.

**Comment by LewisBelton** [comment]
Thanks for the response - https://hastebin.com/huralovixi.rb

**Comment by maddinat0r** [comment]
This is technically an issue with the Docker image you're using. The plugin resolves the Discord API URL by specifying the URL and a service. That service name is then mapped by the OS to a port. The service in this case is https. For whatever reason, the Docker Ubuntu image does not have the https entry in its `/etc/services` file (see https://www.lifewire.com/what-is-etc-services-2196940 for more info).
However, I fixed this in the plugin in 0c76d882223689f9a5cadcbd420364dd64ff1e12, so this problem shouldn't occur anymore starting with the coming update.
In the meantime you could just edit the services file manually and add the https service by yourself to make it work.

**Comment by LewisBelton** [comment]
Hi,

I have this in my '/etc/services' file.. `https        443/tcp       # http protocol over TLS/SSL`

**Comment by Yomanz** [comment]
good night
