### ISSUE TITLE
DCC

### ISSUE THREAD

**Issue by volfikcz** [maddinat0r/samp-discord-connector#95]
Would it be possible to update DCC include for the latest discord-connector? Some callbacks have been removed or are not compatible with the latest version of discord-connector.

I mean this. 

https://forum.sa-mp.com/showthread.php?t=646843

Thanks for response.

**Comment by maddinat0r** [comment]
I'm not the creator of this include, and frankly, this is the wrong place to ask this question. You should try asking in that forum thread.
