### ISSUE TITLE
latest version of mysql isn't compatible with new log core

### ISSUE THREAD

**Issue by bubyygh** [maddinat0r/samp-discord-connector#99]
What now? I was just about to relaunch my server...

**Comment by Zorono** [comment]
wrong repository but anyways it is already reported 
https://github.com/pBlueG/SA-MP-MySQL/issues/215

**Comment by bubyygh** [comment]
Nevermind, mysql works fine with the newest discord connector, but I keep getting [these errors](https://github.com/maddinat0r/samp-discord-connector/issues/100). With and without mysql.
